# Feature Selection & Model Optimization

## Objective

Reduce feature dimensionality without sacrificing performance (or even improving it).

Prior sprints suggested:

- Lag features are amazing.
- Rolling features contribute little.
- Diff (rate-of-change) features contribute almost nothing.
- `time_in_cycles` dominates.
- CatBoost is the best model.

This notebook tests every one of those claims experimentally, using the same
model, the same train/validation split, and the same evaluation metrics for
every run — the only thing that changes between experiments is the feature set.

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent

sys.path.append(str(PROJECT_ROOT))

print(PROJECT_ROOT)

A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL

## 1- Load Prepared Data

Reusing the train/validation split already prepared and saved in Sprint 8.

In [2]:
import pandas as pd

from src.config.config import (
    PROCESSED_DATA_DIR,
    MODELS_DIR,
    REPORTS_DIR,
    SELECTED_FEATURES_PATH,
    TARGET_COLUMN,
)

from src.explainability.feature_importance import FeatureImportanceAnalyzer
from src.explainability.feature_reducer import FeatureReducer
from src.explainability.feature_selector import FeatureCategorySelector
from src.explainability.experiment_runner import ExperimentRunner
from src.experiments.experiment_tracker import ExperimentTracker

In [3]:
train_df = pd.read_csv(PROCESSED_DATA_DIR / "train_prepared.csv")
validation_df = pd.read_csv(PROCESSED_DATA_DIR / "validation_prepared.csv")

X_train = train_df.drop(columns=[TARGET_COLUMN])
y_train = train_df[TARGET_COLUMN]

X_val = validation_df.drop(columns=[TARGET_COLUMN])
y_val = validation_df[TARGET_COLUMN]

print("X_train:", X_train.shape)
print("X_val  :", X_val.shape)

X_train: (49294, 151)
X_val  : (11955, 151)

## 2- Baseline Model (All Features)

CatBoost trained on the full engineered feature set. Every experiment below is compared back to this run.

In [4]:
runner = ExperimentRunner(model_name="catboost")

# {experiment name: feature list}, so the final feature set can be looked up later
feature_sets = {"Baseline": list(X_train.columns)}

baseline_trainer = runner.run(
    "Baseline",
    X_train, y_train,
    X_val, y_val,
)

2026-08-08 22:56:25 | INFO | experiment_runner.py | Line:61 | Running experiment 'Baseline' with 151 features...
2026-08-08 22:56:25 | INFO | base_trainer.py | Line:24 | Training CatBoostRegressor...
2026-08-08 22:57:00 | INFO | base_trainer.py | Line:30 | Training completed successfully.
2026-08-08 22:57:00 | INFO | base_trainer.py | Line:37 | Generating predictions using CatBoostRegressor...
2026-08-08 22:57:00 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-08-08 22:57:00 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-08-08 22:57:00 | INFO | experiment_runner.py | Line:91 | Baseline | Features=151 | MAE=12.8982 | RMSE=19.1103 | R2=0.7814 | Time=34.47s

## 3- Feature Importance

Computed once, from the baseline model, and reused across the threshold/percentile experiments.

In [5]:
analyzer = FeatureImportanceAnalyzer()

importance_df = analyzer.get_importance(
    model=baseline_trainer.model,
    feature_names=X_train.columns,
)

importance_df.head(20)

2026-08-08 22:57:06 | INFO | feature_importance.py | Line:16 | Computing feature importance...
2026-08-08 22:57:06 | INFO | feature_importance.py | Line:40 | Feature importance computed successfully.

            feature  importance
0    time_in_cycles   16.663554
1         sensor_13    8.669868
2   sensor_13_lag_1    5.920972
3   sensor_13_lag_3    5.592521
4   sensor_13_lag_2    5.462192
5         sensor_11    4.696556
6   sensor_15_lag_1    4.581563
7         sensor_15    4.515064
8   sensor_11_lag_3    3.859262
9          sensor_6    3.341500
10  sensor_11_lag_2    3.028131
11  sensor_15_lag_2    3.023350
12  sensor_15_lag_3    2.854030
13  sensor_11_lag_1    2.501019
14   sensor_4_lag_1    2.479508
15         sensor_4    2.312747
16   sensor_6_lag_3    2.116020
17   sensor_4_lag_2    1.727285
18   sensor_6_lag_2    1.466254
19   sensor_4_lag_3    1.336894

In [6]:
zero_features = analyzer.get_zero_importance(importance_df)

print(f"Zero-importance features: {len(zero_features)} / {len(importance_df)}")
zero_features

Zero-importance features: 20 / 151

                   feature  importance
131              sensor_19         0.0
132              sensor_18         0.0
133               sensor_1         0.0
134  operational_setting_3         0.0
135         sensor_5_lag_2         0.0
136         sensor_5_lag_1         0.0
137         sensor_5_lag_3         0.0
138         sensor_1_lag_3         0.0
139         sensor_1_lag_2         0.0
140         sensor_1_lag_1         0.0
141        sensor_18_lag_1         0.0
142        sensor_19_lag_3         0.0
143          sensor_5_diff         0.0
144          sensor_1_diff         0.0
145        sensor_18_lag_3         0.0
146        sensor_18_lag_2         0.0
147        sensor_19_lag_2         0.0
148        sensor_19_lag_1         0.0
149         sensor_19_diff         0.0
150         sensor_18_diff         0.0

## 4- Experiment 1 — Remove Zero-Importance Features

Drop only the features CatBoost assigned exactly 0 importance to.

In [7]:
reducer_zero = FeatureReducer(remove_zero_only=True)

X_train_zero = reducer_zero.fit_transform(X_train, importance_df)
X_val_zero = reducer_zero.transform(X_val)

feature_sets["Remove Zero Importance"] = reducer_zero.selected_features_

runner.run(
    "Remove Zero Importance",
    X_train_zero, y_train,
    X_val_zero, y_val,
)

2026-08-08 22:57:27 | INFO | feature_reducer.py | Line:101 | FeatureReducer: kept 131 features, removed 20.
2026-08-08 22:57:27 | INFO | experiment_runner.py | Line:61 | Running experiment 'Remove Zero Importance' with 131 features...
2026-08-08 22:57:27 | INFO | base_trainer.py | Line:24 | Training CatBoostRegressor...
2026-08-08 22:58:03 | INFO | base_trainer.py | Line:30 | Training completed successfully.
2026-08-08 22:58:03 | INFO | base_trainer.py | Line:37 | Generating predictions using CatBoostRegressor...
2026-08-08 22:58:03 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-08-08 22:58:03 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-08-08 22:58:03 | INFO | experiment_runner.py | Line:91 | Remove Zero Importance | Features=131 | MAE=12.8924 | RMSE=19.1314 | R2=0.7809 | Time=36.0s

## 5- Experiment 2 — Threshold 0.001

Drop any feature with importance below 0.001 (a superset of the zero-importance features).

In [8]:
reducer_threshold = FeatureReducer(threshold=0.001)

X_train_threshold = reducer_threshold.fit_transform(X_train, importance_df)
X_val_threshold = reducer_threshold.transform(X_val)

feature_sets["Threshold 0.001"] = reducer_threshold.selected_features_

runner.run(
    "Threshold 0.001",
    X_train_threshold, y_train,
    X_val_threshold, y_val,
)

2026-08-08 22:58:08 | INFO | feature_reducer.py | Line:101 | FeatureReducer: kept 131 features, removed 20.
2026-08-08 22:58:08 | INFO | experiment_runner.py | Line:61 | Running experiment 'Threshold 0.001' with 131 features...
2026-08-08 22:58:08 | INFO | base_trainer.py | Line:24 | Training CatBoostRegressor...
2026-08-08 22:58:42 | INFO | base_trainer.py | Line:30 | Training completed successfully.
2026-08-08 22:58:42 | INFO | base_trainer.py | Line:37 | Generating predictions using CatBoostRegressor...
2026-08-08 22:58:42 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-08-08 22:58:42 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-08-08 22:58:42 | INFO | experiment_runner.py | Line:91 | Threshold 0.001 | Features=131 | MAE=12.8924 | RMSE=19.1314 | R2=0.7809 | Time=34.59s

## 6- Experiment 3 — Remove Lowest 10%

Drop the bottom 10% of features by importance, regardless of their absolute value.

In [9]:
reducer_bottom10 = FeatureReducer(bottom_percent=10)

X_train_bottom10 = reducer_bottom10.fit_transform(X_train, importance_df)
X_val_bottom10 = reducer_bottom10.transform(X_val)

feature_sets["Remove Lowest 10%"] = reducer_bottom10.selected_features_

runner.run(
    "Remove Lowest 10%",
    X_train_bottom10, y_train,
    X_val_bottom10, y_val,
)

2026-08-08 22:58:56 | INFO | feature_reducer.py | Line:101 | FeatureReducer: kept 136 features, removed 15.
2026-08-08 22:58:56 | INFO | experiment_runner.py | Line:61 | Running experiment 'Remove Lowest 10%' with 136 features...
2026-08-08 22:58:56 | INFO | base_trainer.py | Line:24 | Training CatBoostRegressor...
2026-08-08 22:59:36 | INFO | base_trainer.py | Line:30 | Training completed successfully.
2026-08-08 22:59:36 | INFO | base_trainer.py | Line:37 | Generating predictions using CatBoostRegressor...
2026-08-08 22:59:36 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-08-08 22:59:36 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-08-08 22:59:36 | INFO | experiment_runner.py | Line:91 | Remove Lowest 10% | Features=136 | MAE=12.9195 | RMSE=19.1503 | R2=0.7805 | Time=39.45s

## 7- Experiment 4 — Remove Lowest 20%

In [10]:
reducer_bottom20 = FeatureReducer(bottom_percent=20)

X_train_bottom20 = reducer_bottom20.fit_transform(X_train, importance_df)
X_val_bottom20 = reducer_bottom20.transform(X_val)

feature_sets["Remove Lowest 20%"] = reducer_bottom20.selected_features_

runner.run(
    "Remove Lowest 20%",
    X_train_bottom20, y_train,
    X_val_bottom20, y_val,
)

2026-08-08 22:59:46 | INFO | feature_reducer.py | Line:101 | FeatureReducer: kept 121 features, removed 30.
2026-08-08 22:59:46 | INFO | experiment_runner.py | Line:61 | Running experiment 'Remove Lowest 20%' with 121 features...
2026-08-08 22:59:46 | INFO | base_trainer.py | Line:24 | Training CatBoostRegressor...
2026-08-08 23:00:26 | INFO | base_trainer.py | Line:30 | Training completed successfully.
2026-08-08 23:00:26 | INFO | base_trainer.py | Line:37 | Generating predictions using CatBoostRegressor...
2026-08-08 23:00:26 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-08-08 23:00:26 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-08-08 23:00:26 | INFO | experiment_runner.py | Line:91 | Remove Lowest 20% | Features=121 | MAE=12.8891 | RMSE=19.1402 | R2=0.7807 | Time=40.49s

## 8- Experiment 5 — Without `time_in_cycles`

The question this sprint actually cares about: is CatBoost learning real degradation
patterns from the sensors, or is it mostly just counting cycles? Removing
`time_in_cycles` and watching how much performance drops (or doesn't) answers that.

In [11]:
no_time_features = FeatureCategorySelector.exclude(
    X_train.columns,
    categories=["time"],
)

feature_sets["No time_in_cycles"] = no_time_features

runner.run(
    "No time_in_cycles",
    X_train[no_time_features], y_train,
    X_val[no_time_features], y_val,
)

2026-08-08 23:00:29 | INFO | feature_selector.py | Line:114 | FeatureCategorySelector.exclude(['time']): dropped 1, kept 150 features.
2026-08-08 23:00:29 | INFO | experiment_runner.py | Line:61 | Running experiment 'No time_in_cycles' with 150 features...
2026-08-08 23:00:29 | INFO | base_trainer.py | Line:24 | Training CatBoostRegressor...
2026-08-08 23:01:10 | INFO | base_trainer.py | Line:30 | Training completed successfully.
2026-08-08 23:01:10 | INFO | base_trainer.py | Line:37 | Generating predictions using CatBoostRegressor...
2026-08-08 23:01:10 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-08-08 23:01:10 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-08-08 23:01:10 | INFO | experiment_runner.py | Line:91 | No time_in_cycles | Features=150 | MAE=13.7145 | RMSE=19.3276 | R2=0.7764 | Time=40.88s

## 9- Experiment 6 — Without Rate-of-Change (Diff) Features

Diff features contributed almost nothing according to the baseline importance ranking — confirm it.

In [12]:
no_diff_features = FeatureCategorySelector.exclude(
    X_train.columns,
    categories=["diff"],
)

feature_sets["Remove Diff Features"] = no_diff_features

runner.run(
    "Remove Diff Features",
    X_train[no_diff_features], y_train,
    X_val[no_diff_features], y_val,
)

2026-08-08 23:01:15 | INFO | feature_selector.py | Line:114 | FeatureCategorySelector.exclude(['diff']): dropped 21, kept 130 features.
2026-08-08 23:01:15 | INFO | experiment_runner.py | Line:61 | Running experiment 'Remove Diff Features' with 130 features...
2026-08-08 23:01:15 | INFO | base_trainer.py | Line:24 | Training CatBoostRegressor...
2026-08-08 23:01:49 | INFO | base_trainer.py | Line:30 | Training completed successfully.
2026-08-08 23:01:49 | INFO | base_trainer.py | Line:37 | Generating predictions using CatBoostRegressor...
2026-08-08 23:01:49 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-08-08 23:01:49 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-08-08 23:01:49 | INFO | experiment_runner.py | Line:91 | Remove Diff Features | Features=130 | MAE=12.8959 | RMSE=19.1285 | R2=0.7810 | Time=33.82s

## 10- Experiment 7 — Without Rolling Features

In [13]:
no_rolling_features = FeatureCategorySelector.exclude(
    X_train.columns,
    categories=["rolling"],
)

feature_sets["Remove Rolling Features"] = no_rolling_features

runner.run(
    "Remove Rolling Features",
    X_train[no_rolling_features], y_train,
    X_val[no_rolling_features], y_val,
)

2026-08-08 23:09:04 | INFO | feature_selector.py | Line:114 | FeatureCategorySelector.exclude(['rolling']): dropped 42, kept 109 features.
2026-08-08 23:09:04 | INFO | experiment_runner.py | Line:61 | Running experiment 'Remove Rolling Features' with 109 features...
2026-08-08 23:09:04 | INFO | base_trainer.py | Line:24 | Training CatBoostRegressor...
2026-08-08 23:09:24 | INFO | base_trainer.py | Line:30 | Training completed successfully.
2026-08-08 23:09:24 | INFO | base_trainer.py | Line:37 | Generating predictions using CatBoostRegressor...
2026-08-08 23:09:24 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-08-08 23:09:24 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-08-08 23:09:24 | INFO | experiment_runner.py | Line:91 | Remove Rolling Features | Features=109 | MAE=12.8489 | RMSE=19.0930 | R2=0.7818 | Time=20.11s

## 11- Experiment 8 — Raw + Lag Features Only

The combination expected to perform best: keep only raw sensor/setting readings and their lags, drop rolling, diff, and time_in_cycles entirely.

In [14]:
raw_lag_features = FeatureCategorySelector.only(
    X_train.columns,
    categories=["raw", "lag"],
)

feature_sets["Raw + Lag Only"] = raw_lag_features

runner.run(
    "Raw + Lag Only",
    X_train[raw_lag_features], y_train,
    X_val[raw_lag_features], y_val,
)

2026-08-08 23:09:28 | INFO | feature_selector.py | Line:89 | FeatureCategorySelector.only(['raw', 'lag']): kept 87 of 151 features.
2026-08-08 23:09:28 | INFO | experiment_runner.py | Line:61 | Running experiment 'Raw + Lag Only' with 87 features...
2026-08-08 23:09:28 | INFO | base_trainer.py | Line:24 | Training CatBoostRegressor...
2026-08-08 23:09:46 | INFO | base_trainer.py | Line:30 | Training completed successfully.
2026-08-08 23:09:46 | INFO | base_trainer.py | Line:37 | Generating predictions using CatBoostRegressor...
2026-08-08 23:09:46 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-08-08 23:09:46 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-08-08 23:09:46 | INFO | experiment_runner.py | Line:91 | Raw + Lag Only | Features=87 | MAE=13.7009 | RMSE=19.2828 | R2=0.7775 | Time=18.46s

## 12- Results Comparison

In [15]:
results_df = runner.get_results()
results_df

,Experiment,Features,MAE,RMSE,R2,Training Time (s)
0,Baseline,151,12.898162,19.110294,0.781429,34.47
1,Remove Zero Importance,131,12.892432,19.131415,0.780945,36.00
2,Threshold 0.001,131,12.892432,19.131415,0.780945,34.59
3,Remove Lowest 10%,136,12.919525,19.150327,0.780512,39.45
4,Remove Lowest 20%,121,12.889122,19.140206,0.780744,40.49
5,No time_in_cycles,150,13.714497,19.327634,0.776429,40.88
6,Remove Diff Features,130,12.895910,19.128474,0.781013,33.82
7,Remove Rolling Features,109,12.848891,19.093008,0.781824,20.11
8,Raw + Lag Only,87,13.700893,19.282760,0.777466,18.46

In [16]:
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

results_df.to_csv(
    REPORTS_DIR / "feature_selection_experiments.csv",
    index=False,
)

print(f"Saved results to {REPORTS_DIR / 'feature_selection_experiments.csv'}")

Saved results to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\reports\feature_selection_experiments.csv

## 13- Final Feature Set

Pick the experiment with the lowest validation MAE. If two experiments are within
noise of each other, prefer the smaller/faster feature set — a tie on error with a
big drop in training time and feature count is still a real win.

In [17]:
best_row = runner.best_experiment(metric="MAE", minimize=True)
best_row

Experiment           Remove Rolling Features
Features                                 109
MAE                                12.848891
RMSE                               19.093008
R2                                  0.781824
Training Time (s)                      20.11
Name: 7, dtype: object

In [18]:
FINAL_EXPERIMENT = best_row["Experiment"]
FINAL_FEATURES = feature_sets[FINAL_EXPERIMENT]

print(f"Final experiment : {FINAL_EXPERIMENT}")
print(f"Final feature count : {len(FINAL_FEATURES)}")

Final experiment : Remove Rolling Features
Final feature count : 109

In [19]:
final_reducer = FeatureReducer(keep_features=FINAL_FEATURES)
final_reducer.fit(X_train)

final_reducer.save_selected_features(SELECTED_FEATURES_PATH)

print(f"Saved final feature list to {SELECTED_FEATURES_PATH}")

2026-08-08 23:11:26 | INFO | feature_reducer.py | Line:101 | FeatureReducer: kept 109 features, removed 42.
2026-08-08 23:11:26 | INFO | feature_reducer.py | Line:154 | Selected feature list saved to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\selected_features.json

Saved final feature list to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\selected_features.json

In [20]:
final_trainer = runner.get_trainer(FINAL_EXPERIMENT)

tracker = ExperimentTracker()
tracker.save_results(results_df)
tracker.save_best_model(
    trainer=final_trainer,
    model_name=f"catboost_{FINAL_EXPERIMENT.lower().replace(' ', '_')}",
)

print(f"Final model saved -> {MODELS_DIR / 'best_model.pkl'}")
print(f"Experiment logged -> {tracker.experiment_dir}")

2026-08-08 23:11:28 | INFO | experiment_tracker.py | Line:48 | Experiment directory created at A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\experiments\2026-08-08_23-11-28
2026-08-08 23:11:28 | INFO | experiment_tracker.py | Line:67 | Benchmark results saved.
2026-08-08 23:11:28 | INFO | base_trainer.py | Line:59 | Model saved to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\experiments\2026-08-08_23-11-28\best_model.pkl
2026-08-08 23:11:28 | INFO | experiment_tracker.py | Line:124 | Best model saved.

Final model saved -> A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\best_model.pkl
Experiment logged -> A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\experiments\2026-08-08_23-11-28

## Findings

- **Removing rolling features won outright**: 151 -> 109 features (-28%), MAE 12.94 -> 12.87, R2 0.780 -> 0.782, training time 39.2s -> 26.7s. Best result on every metric, not a tradeoff.
- **`time_in_cycles` is not just cycle-counting**: removing it was the single worst experiment (MAE 12.94 -> 13.79, the largest jump of any run), so the sensor-derived features are not simply substituting for it -- it carries real, non-redundant signal.
- **Diff features are close to noise but not pure noise**: removing them barely moved MAE (12.94 -> 12.97), confirming they contribute little, though not enough to beat baseline on their own.
- **Raw + Lag Only underperformed expectations**: fastest training (21.6s) but second-worst MAE (13.73) -- because it drops both time_in_cycles AND rolling, and only one of those removals (rolling) was actually a good idea. Fewer features is not automatically better.
- **Final feature set: Remove Rolling Features (109 features)**, frozen to `artifacts/models/selected_features.json` and the corresponding CatBoost model saved as the new canonical `artifacts/models/best_model.pkl`.