# Full Pipeline: Raw Data -> Tuned Multi-Model Ensemble

## Goal

Self-contained, start to finish: raw NASA files -> validation -> RUL generation ->
feature engineering -> feature selection -> train/validation split -> scaling ->
hyperparameter tuning (CatBoost + XGBoost + LightGBM, all three, not just CatBoost) ->
weighted ensemble -> evaluation on validation **and** the official test set.

**Does not assume any prior artifact exists** — `train_prepared.csv`,
`selected_features.json`, `feature_scaler.pkl` are all rebuilt from the raw files in this
notebook, not loaded from disk. Safe to run after a clean checkout or a deleted
`artifacts/` folder — verified by testing it with `artifacts/` deleted before running.

Every tuning trial is automatically logged to MLflow (`BaseTrainer`'s built-in tracking)
— no separate logging step.

**Adjust `N_TRIALS` below before a real run** — defaults low here for a quick correctness
check; bump to 20-30+ per model for a real search.

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent
sys.path.append(str(PROJECT_ROOT))
print(PROJECT_ROOT)

A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL

In [2]:
N_TRIALS = 20  # per model -- increase for a real search
RUN_TEST_EVAL = True  # official test-set evaluation at the end

In [3]:
import json
import joblib
import pandas as pd

from src.config.config import (
    TRAIN_DATA_PATH, TEST_DATA_PATH, RUL_DATA_PATH,
    MODELS_DIR, REPORTS_DIR, SCALERS_DIR, SELECTED_FEATURES_PATH,
    VALIDATION_SIZE, RANDOM_STATE, DEFAULT_RUL_CAP,
    ROLLING_WINDOW, LAGS, ENGINE_COLUMN, TARGET_COLUMN,
)
from src.utils.constant import SENSOR_COLUMNS
from src.data.loader import DataLoader
from src.data.validator import DataValidator
from src.preprocessing.rul_generator import RULGenerator
from src.preprocessing.feature_engineer import FeatureEngineer
from src.preprocessing.data_splitter import DataSplitter
from src.preprocessing.feature_scaler import FeatureScaler
from src.explainability.feature_selector import FeatureCategorySelector
from src.explainability.feature_reducer import FeatureReducer
from src.optimization.hyperparameter_tuner import ModelTuner
from src.models.model_factory import ModelFactory
from src.models.base_trainer import BaseTrainer
from src.models.ensemble import EnsembleModel
from src.evaluation.evaluator import RegressionEvaluator

a:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1- Load Raw Data

In [4]:
loader = DataLoader(train_path=TRAIN_DATA_PATH, test_path=TEST_DATA_PATH, rul_path=RUL_DATA_PATH)
train_raw = loader.load_train()
test_raw = loader.load_test()
rul_raw = loader.load_rul()

print(f"train_FD004: {train_raw.shape}  test_FD004: {test_raw.shape}  RUL_FD004: {rul_raw.shape}")

2026-09-01 11:59:12 | INFO | loader.py | Line:18 | Reading train_FD004.txt
2026-09-01 11:59:15 | INFO | loader.py | Line:21 | train_FD004.txt Loaded Successfully
2026-09-01 11:59:15 | INFO | loader.py | Line:18 | Reading test_FD004.txt
2026-09-01 11:59:17 | INFO | loader.py | Line:21 | test_FD004.txt Loaded Successfully
2026-09-01 11:59:17 | INFO | loader.py | Line:18 | Reading RUL_FD004.txt
2026-09-01 11:59:17 | INFO | loader.py | Line:21 | RUL_FD004.txt Loaded Successfully

train_FD004: (61249, 26)  test_FD004: (41214, 26)  RUL_FD004: (248, 1)

## 2- Validate

In [5]:
report = DataValidator(train_raw, test_raw, rul_raw).validate_all()
report

2026-09-01 11:59:22 | INFO | validator.py | Line:40 | Validating training dataset...
2026-09-01 11:59:22 | INFO | validator.py | Line:50 | Validating testing dataset...
2026-09-01 11:59:22 | INFO | validator.py | Line:60 | Validating RUL dataset...

{'train': {'valid': True, 'errors': [], 'warnings': []},
 'test': {'valid': True, 'errors': [], 'warnings': []},
 'rul': {'valid': True, 'errors': [], 'warnings': ['Duplicate rows found.']}}

## 3- Generate RUL

In [6]:
train_with_rul = RULGenerator(train_raw).generate(cap=DEFAULT_RUL_CAP)
print(f"cap={DEFAULT_RUL_CAP}  RUL range: [{train_with_rul[TARGET_COLUMN].min()}, {train_with_rul[TARGET_COLUMN].max()}]")

2026-09-01 12:04:41 | INFO | rul_generator.py | Line:82 | Generating Remaining Useful Life (RUL)...
2026-09-01 12:04:41 | INFO | rul_generator.py | Line:92 | Applying RUL cap = 150
2026-09-01 12:04:41 | INFO | rul_generator.py | Line:96 | RUL generated successfully.

cap=150  RUL range: [0, 150]

## 4- Feature Engineering

In [7]:
engineer = FeatureEngineer(sensor_columns=SENSOR_COLUMNS, rolling_window=ROLLING_WINDOW, lags=LAGS)
feature_df = engineer.transform(train_with_rul)
print(f"Engineered: {feature_df.shape[1]} columns ({feature_df.shape[1] - 2} features)")

2026-09-01 12:05:11 | INFO | feature_engineer.py | Line:50 | Starting Feature Engineering...
2026-09-01 12:05:11 | INFO | feature_engineer.py | Line:119 | Generating Rolling Mean features...
2026-09-01 12:05:13 | INFO | feature_engineer.py | Line:148 | Generating Rolling Std features...
2026-09-01 12:05:15 | INFO | feature_engineer.py | Line:179 | Generating Lag Features...
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
2026-09-01 12:05:15 | INFO | feature_engineer.py | Line:205 | Generating Rate of Change features...
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
2026-09-01 12:05:15 | INFO | feature_engineer.py | Line:61 | Feature Engineering completed successfully.

Engineered: 153 columns (151 features)

## 5- Feature Selection

Reproduces Sprint 10's real, already-validated result (removing rolling features was the
best of 9 real experiments) rather than re-running the full experiment sweep — same
decision, deterministically reapplied.

In [8]:
all_columns = [c for c in feature_df.columns if c not in (ENGINE_COLUMN, TARGET_COLUMN)]
final_features = FeatureCategorySelector.exclude(all_columns, categories=["rolling"])
print(f"Selected {len(final_features)} features")

MODELS_DIR.mkdir(parents=True, exist_ok=True)
reducer = FeatureReducer(keep_features=final_features)
reducer.fit(feature_df[all_columns])
reducer.save_selected_features(SELECTED_FEATURES_PATH)

2026-09-01 12:05:35 | INFO | feature_selector.py | Line:114 | FeatureCategorySelector.exclude(['rolling']): dropped 42, kept 109 features.
2026-09-01 12:05:35 | INFO | feature_reducer.py | Line:101 | FeatureReducer: kept 109 features, removed 42.
2026-09-01 12:05:35 | INFO | feature_reducer.py | Line:154 | Selected feature list saved to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\selected_features.json

Selected 109 features

## 6- Train / Validation Split — by Engine, Never by Row

In [9]:
splitter = DataSplitter(test_size=VALIDATION_SIZE, engine_column=ENGINE_COLUMN, random_state=RANDOM_STATE)
train_split, val_split = splitter.split(feature_df)

print(f"Train: {train_split[ENGINE_COLUMN].nunique()} engines ({train_split.shape[0]} rows)")
print(f"Val  : {val_split[ENGINE_COLUMN].nunique()} engines ({val_split.shape[0]} rows)")

2026-09-01 12:06:11 | INFO | data_splitter.py | Line:35 | Starting engine-based train/validation split...
2026-09-01 12:06:13 | INFO | data_splitter.py | Line:67 | Train Engines: 199 | Validation Engines: 50
2026-09-01 12:06:13 | INFO | data_splitter.py | Line:72 | Data splitting completed successfully.

Train: 199 engines (49294 rows)
Val  : 50 engines (11955 rows)

## 7- Scaling — Fit on Train Only

In [10]:
scaler = FeatureScaler()
X_train = scaler.fit_transform(train_split[final_features])
X_val = scaler.transform(val_split[final_features])
y_train = train_split[TARGET_COLUMN].reset_index(drop=True)
y_val = val_split[TARGET_COLUMN].reset_index(drop=True)

SCALERS_DIR.mkdir(parents=True, exist_ok=True)
scaler.save(SCALERS_DIR / "feature_scaler.pkl")
print(f"X_train: {X_train.shape}  X_val: {X_val.shape}")

2026-09-01 12:06:27 | INFO | feature_scaler.py | Line:33 | Fitting Feature Scaler...

2026-09-01 12:06:28 | INFO | feature_scaler.py | Line:37 | Feature Scaler fitted successfully.
2026-09-01 12:06:28 | INFO | feature_scaler.py | Line:44 | Transforming features...
2026-09-01 12:06:28 | INFO | feature_scaler.py | Line:60 | Feature transformation completed.
2026-09-01 12:06:28 | INFO | feature_scaler.py | Line:44 | Transforming features...
2026-09-01 12:06:28 | INFO | feature_scaler.py | Line:60 | Feature transformation completed.
2026-09-01 12:06:28 | INFO | feature_scaler.py | Line:89 | Scaler saved to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\scalers\feature_scaler.pkl

X_train: (49294, 109)  X_val: (11955, 109)

## 8- Tune Each Model

Same `ModelTuner`, same mechanism, model-specific search space (depth, learning rate,
iterations/trees, regularization, subsampling). Every trial auto-logs to MLflow.

In [11]:
evaluator = RegressionEvaluator()
tuned_models = {}
val_results = []

for model_name in ["catboost", "xgboost", "lightgbm"]:

    print(f"--- Tuning {model_name} ---")
    tuner = ModelTuner(model_name, X_train, y_train, X_val, y_val, random_state=RANDOM_STATE)
    tuner.run(n_trials=N_TRIALS, show_progress_bar=True)

    best_params = tuner.best_params()
    print(f"{model_name} best params: {best_params}")

    final_model = ModelFactory.create(model_name, **best_params)
    final_trainer = BaseTrainer(
        final_model,
        run_name=f"{model_name}_final_tuned",
        tags={"model_family": model_name, "stage": "final_tuned_model"},
    )
    metrics = final_trainer.train(X_train, y_train, X_val, y_val)
    print(f"{model_name} final validation metrics: {metrics}\n")

    tuned_models[model_name] = final_model
    val_results.append({"Model": model_name, "Stage": "tuned_individual", **metrics})

    joblib.dump(final_model, MODELS_DIR / f"{model_name}_tuned.pkl")
    with open(MODELS_DIR / f"{model_name}_best_params.json", "w") as f:
        json.dump({"params": best_params, "metrics": metrics}, f, indent=2)

[I 2026-09-01 12:06:33,614] A new study created in memory with name: catboost_rul_optimization
2026-09-01 12:06:33 | INFO | hyperparameter_tuner.py | Line:142 | Starting Optuna search for catboost: 20 trials, search space = ['depth', 'learning_rate', 'iterations', 'l2_leaf_reg', 'subsample', 'random_strength']

--- Tuning catboost ---

  0%|          | 0/20 [00:00<?, ?it/s]2026/09/01 12:07:23 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/09/01 12:07:23 INFO mlflow.store.db.utils: Updating database tables
2026/09/01 12:07:29 INFO mlflow.tracking.fluent: Experiment with name 'predictive-maintenance-rul' does not exist. Creating a new experiment.
2026-09-01 12:07:29 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...
2026-09-01 12:07:52 | INFO | base_trainer.py | Line:80 | Training completed successfully in 23.23s.
2026-09-01 12:07:52 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:07:52 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:07:52 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:07:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:08:14 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:08:14 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=a2161f805bac4c518957d248f48d4f63
2026-09-01 12:08:14 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 0 | MAE=18.1824 | RMSE=25.2920 | R2=0.7453 | Time=44.85s | params={'depth': 6, 'learning_rate': 0.2536999076681772, 'iterations': 1152, 'l2_leaf_reg': 6.387926357773329, 'subsample': 0.5780093202212182, 'random_strength': 1.5599452033620265}
Best trial: 0. Best value: 18.1824:   5%|▌         | 1/20 [01:40<31:56, 100.84s/it]2026-09-01 12:08:14 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:08:14,456] Trial 0 finished with value: 18.18240061904868 and parameters: {'depth': 6, 'learning_rate': 0.2536999076681772, 'iterations': 1152, 'l2_leaf_reg': 6.387926357773329, 'subsample': 0.5780093202212182, 'random_strength': 1.5599452033620265}. Best is trial 0 with value: 18.18240061904868.

2026-09-01 12:08:25 | INFO | base_trainer.py | Line:80 | Training completed successfully in 10.84s.
2026-09-01 12:08:25 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:08:25 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:08:25 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:08:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:08:35 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:08:35 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=a577188716034963864e7a68a9ba1565
2026-09-01 12:08:35 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 1 | MAE=18.1402 | RMSE=25.0335 | R2=0.7505 | Time=21.45s | params={'depth': 4, 'learning_rate': 0.19030368381735815, 'iterations': 982, 'l2_leaf_reg': 7.372653200164409, 'subsample': 0.5102922471479012, 'random_strength': 9.699098521619943}
Best trial: 1. Best value: 18.1402:  10%|█         | 2/20 [02:02<16:14, 54.17s/it] 2026-09-01 12:08:35 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:08:35,938] Trial 1 finished with value: 18.140210782432042 and parameters: {'depth': 4, 'learning_rate': 0.19030368381735815, 'iterations': 982, 'l2_leaf_reg': 7.372653200164409, 'subsample': 0.5102922471479012, 'random_strength': 9.699098521619943}. Best is trial 1 with value: 18.140210782432042.

2026-09-01 12:09:28 | INFO | base_trainer.py | Line:80 | Training completed successfully in 52.93s.
2026-09-01 12:09:28 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:09:28 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:09:28 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:09:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:09:41 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:09:41 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=9a3bab4af96842c1ae74d19cb0238bc3
2026-09-01 12:09:41 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 2 | MAE=19.7925 | RMSE=26.6884 | R2=0.7164 | Time=65.85s | params={'depth': 9, 'learning_rate': 0.020589728197687916, 'iterations': 436, 'l2_leaf_reg': 2.650640588680904, 'subsample': 0.6521211214797689, 'random_strength': 5.247564316322379}
Best trial: 1. Best value: 18.1402:  15%|█▌        | 3/20 [03:08<16:51, 59.52s/it]2026-09-01 12:09:41 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:09:41,840] Trial 2 finished with value: 19.792454307715474 and parameters: {'depth': 9, 'learning_rate': 0.020589728197687916, 'iterations': 436, 'l2_leaf_reg': 2.650640588680904, 'subsample': 0.6521211214797689, 'random_strength': 5.247564316322379}. Best is trial 1 with value: 18.140210782432042.

2026-09-01 12:10:24 | INFO | base_trainer.py | Line:80 | Training completed successfully in 42.27s.
2026-09-01 12:10:24 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:10:24 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:10:24 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:10:24 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:10:37 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:10:37 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=488a789d33184b968e25b0674a67a987
2026-09-01 12:10:37 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 3 | MAE=18.0614 | RMSE=25.1044 | R2=0.7490 | Time=55.28s | params={'depth': 7, 'learning_rate': 0.02692655251486473, 'iterations': 996, 'l2_leaf_reg': 2.2554447458683766, 'subsample': 0.6460723242676091, 'random_strength': 3.663618432936917}
Best trial: 3. Best value: 18.0614:  20%|██        | 4/20 [04:03<15:25, 57.87s/it]2026-09-01 12:10:37 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:10:37,171] Trial 3 finished with value: 18.06142674135793 and parameters: {'depth': 7, 'learning_rate': 0.02692655251486473, 'iterations': 996, 'l2_leaf_reg': 2.2554447458683766, 'subsample': 0.6460723242676091, 'random_strength': 3.663618432936917}. Best is trial 3 with value: 18.06142674135793.

2026-09-01 12:10:57 | INFO | base_trainer.py | Line:80 | Training completed successfully in 20.25s.
2026-09-01 12:10:57 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:10:57 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:10:57 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:10:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:11:07 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:11:07 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=afc0856eac7947c484b801945f85c2fd
2026-09-01 12:11:07 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 4 | MAE=17.8627 | RMSE=24.9098 | R2=0.7529 | Time=30.30s | params={'depth': 7, 'learning_rate': 0.14447746112718687, 'iterations': 459, 'l2_leaf_reg': 5.628109945722504, 'subsample': 0.7962072844310213, 'random_strength': 0.46450412719997725}
Best trial: 4. Best value: 17.8627:  25%|██▌       | 5/20 [04:33<11:59, 47.94s/it]2026-09-01 12:11:07 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:11:07,501] Trial 4 finished with value: 17.862661997266915 and parameters: {'depth': 7, 'learning_rate': 0.14447746112718687, 'iterations': 459, 'l2_leaf_reg': 5.628109945722504, 'subsample': 0.7962072844310213, 'random_strength': 0.46450412719997725}. Best is trial 4 with value: 17.862661997266915.

2026-09-01 12:11:28 | INFO | base_trainer.py | Line:80 | Training completed successfully in 21.27s.
2026-09-01 12:11:28 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:11:28 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:11:28 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:11:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:11:39 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:11:39 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=0116f9f5e563473fa0d562d0460cb128
2026-09-01 12:11:39 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 5 | MAE=21.0958 | RMSE=27.3256 | R2=0.7027 | Time=31.57s | params={'depth': 8, 'learning_rate': 0.0178601378893971, 'iterations': 284, 'l2_leaf_reg': 9.539969835279999, 'subsample': 0.9828160165372797, 'random_strength': 8.08397348116461}
Best trial: 4. Best value: 17.8627:  30%|███       | 6/20 [05:05<09:53, 42.39s/it]2026-09-01 12:11:39 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:11:39,111] Trial 5 finished with value: 21.095789198452334 and parameters: {'depth': 8, 'learning_rate': 0.0178601378893971, 'iterations': 284, 'l2_leaf_reg': 9.539969835279999, 'subsample': 0.9828160165372797, 'random_strength': 8.08397348116461}. Best is trial 4 with value: 17.862661997266915.

2026-09-01 12:12:06 | INFO | base_trainer.py | Line:80 | Training completed successfully in 27.42s.
2026-09-01 12:12:06 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:12:06 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:12:06 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:12:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:12:17 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:12:18 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=6fc472abf55a45c8b03cbebbe0449f7e
2026-09-01 12:12:18 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 6 | MAE=19.2598 | RMSE=26.1455 | R2=0.7278 | Time=38.96s | params={'depth': 6, 'learning_rate': 0.013940346079873234, 'iterations': 1090, 'l2_leaf_reg': 4.961372443656412, 'subsample': 0.5610191174223894, 'random_strength': 4.951769101112702}
Best trial: 4. Best value: 17.8627:  35%|███▌      | 7/20 [05:44<08:56, 41.28s/it]2026-09-01 12:12:18 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:12:18,103] Trial 6 finished with value: 19.259829404482637 and parameters: {'depth': 6, 'learning_rate': 0.013940346079873234, 'iterations': 1090, 'l2_leaf_reg': 4.961372443656412, 'subsample': 0.5610191174223894, 'random_strength': 4.951769101112702}. Best is trial 4 with value: 17.862661997266915.

2026-09-01 12:12:26 | INFO | base_trainer.py | Line:80 | Training completed successfully in 8.12s.
2026-09-01 12:12:26 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:12:26 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:12:26 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:12:26 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:12:39 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:12:39 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=807a39df0cf94dd3bfde40701c5692ec
2026-09-01 12:12:39 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 7 | MAE=18.1972 | RMSE=25.1164 | R2=0.7488 | Time=21.28s | params={'depth': 4, 'learning_rate': 0.22038218939289875, 'iterations': 536, 'l2_leaf_reg': 6.962700559185838, 'subsample': 0.6558555380447055, 'random_strength': 5.200680211778108}
Best trial: 4. Best value: 17.8627:  40%|████      | 8/20 [06:05<06:59, 34.93s/it]2026-09-01 12:12:39 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:12:39,435] Trial 7 finished with value: 18.19721488181527 and parameters: {'depth': 4, 'learning_rate': 0.22038218939289875, 'iterations': 536, 'l2_leaf_reg': 6.962700559185838, 'subsample': 0.6558555380447055, 'random_strength': 5.200680211778108}. Best is trial 4 with value: 17.862661997266915.

2026-09-01 12:13:37 | INFO | base_trainer.py | Line:80 | Training completed successfully in 58.07s.
2026-09-01 12:13:37 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:13:37 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:13:37 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:13:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:13:48 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:13:48 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=96eb799a05eb4a26ba53992248724cbd
2026-09-01 12:13:48 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 8 | MAE=18.1424 | RMSE=25.1564 | R2=0.7480 | Time=69.43s | params={'depth': 7, 'learning_rate': 0.01875220945578641, 'iterations': 1461, 'l2_leaf_reg': 7.976195410250031, 'subsample': 0.9697494707820946, 'random_strength': 8.948273504276488}
Best trial: 4. Best value: 17.8627:  45%|████▌     | 9/20 [07:15<08:23, 45.73s/it]2026-09-01 12:13:48 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:13:48,921] Trial 8 finished with value: 18.14235036525757 and parameters: {'depth': 7, 'learning_rate': 0.01875220945578641, 'iterations': 1461, 'l2_leaf_reg': 7.976195410250031, 'subsample': 0.9697494707820946, 'random_strength': 8.948273504276488}. Best is trial 4 with value: 17.862661997266915.

2026-09-01 12:14:07 | INFO | base_trainer.py | Line:80 | Training completed successfully in 18.75s.
2026-09-01 12:14:07 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:14:07 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:14:07 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:14:07 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:14:19 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:14:19 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=63332c17ef864449aca20b3f8e7a5238
2026-09-01 12:14:19 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 9 | MAE=18.0401 | RMSE=25.1893 | R2=0.7473 | Time=30.51s | params={'depth': 8, 'learning_rate': 0.22999586428143728, 'iterations': 315, 'l2_leaf_reg': 2.763845761772307, 'subsample': 0.522613644455269, 'random_strength': 3.2533033076326436}
Best trial: 4. Best value: 17.8627:  50%|█████     | 10/20 [07:45<06:50, 41.05s/it]2026-09-01 12:14:19 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:14:19,470] Trial 9 finished with value: 18.04014135331631 and parameters: {'depth': 8, 'learning_rate': 0.22999586428143728, 'iterations': 315, 'l2_leaf_reg': 2.763845761772307, 'subsample': 0.522613644455269, 'random_strength': 3.2533033076326436}. Best is trial 4 with value: 17.862661997266915.

2026-09-01 12:17:40 | INFO | base_trainer.py | Line:80 | Training completed successfully in 200.48s.
2026-09-01 12:17:40 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:17:40 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:17:40 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:17:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:17:53 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:17:53 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=0e1f2e3bcc434f21b2fbaa73fada7a6b
2026-09-01 12:17:53 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 10 | MAE=17.7734 | RMSE=24.9355 | R2=0.7524 | Time=213.67s | params={'depth': 10, 'learning_rate': 0.06690992453172909, 'iterations': 683, 'l2_leaf_reg': 4.662344222665566, 'subsample': 0.8301310219655023, 'random_strength': 0.38725199961183154}
Best trial: 10. Best value: 17.7734:  55%|█████▌    | 11/20 [11:19<14:05, 93.91s/it]2026-09-01 12:17:53 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:17:53,256] Trial 10 finished with value: 17.77335696683235 and parameters: {'depth': 10, 'learning_rate': 0.06690992453172909, 'iterations': 683, 'l2_leaf_reg': 4.662344222665566, 'subsample': 0.8301310219655023, 'random_strength': 0.38725199961183154}. Best is trial 10 with value: 17.77335696683235.

2026-09-01 12:21:25 | INFO | base_trainer.py | Line:80 | Training completed successfully in 212.11s.
2026-09-01 12:21:25 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:21:25 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:21:25 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:21:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:21:36 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:21:36 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=8a71f750e5d64b64af811bb29e9e6b00
2026-09-01 12:21:36 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 11 | MAE=17.7162 | RMSE=24.8602 | R2=0.7539 | Time=223.06s | params={'depth': 10, 'learning_rate': 0.08353087730210125, 'iterations': 670, 'l2_leaf_reg': 4.416438190782012, 'subsample': 0.8231273281884821, 'random_strength': 0.053093170935556544}
Best trial: 11. Best value: 17.7162:  60%|██████    | 12/20 [15:02<17:45, 133.23s/it]2026-09-01 12:21:36 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:21:36,413] Trial 11 finished with value: 17.716156801589168 and parameters: {'depth': 10, 'learning_rate': 0.08353087730210125, 'iterations': 670, 'l2_leaf_reg': 4.416438190782012, 'subsample': 0.8231273281884821, 'random_strength': 0.053093170935556544}. Best is trial 11 with value: 17.716156801589168.

2026-09-01 12:26:08 | INFO | base_trainer.py | Line:80 | Training completed successfully in 271.68s.
2026-09-01 12:26:08 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:26:08 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:26:08 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:26:08 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:26:23 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:26:23 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=e26c2b59f318400696c3e1c78079b092
2026-09-01 12:26:23 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 12 | MAE=17.7557 | RMSE=24.8985 | R2=0.7531 | Time=287.28s | params={'depth': 10, 'learning_rate': 0.0776195669164356, 'iterations': 733, 'l2_leaf_reg': 4.1642972288438544, 'subsample': 0.8423092026960021, 'random_strength': 0.04172495219693942}
Best trial: 11. Best value: 17.7162:  65%|██████▌   | 13/20 [19:50<20:59, 179.93s/it]2026-09-01 12:26:23 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:26:23,793] Trial 12 finished with value: 17.755718508430235 and parameters: {'depth': 10, 'learning_rate': 0.0776195669164356, 'iterations': 733, 'l2_leaf_reg': 4.1642972288438544, 'subsample': 0.8423092026960021, 'random_strength': 0.04172495219693942}. Best is trial 11 with value: 17.716156801589168.

2026-09-01 12:30:34 | INFO | base_trainer.py | Line:80 | Training completed successfully in 250.37s.
2026-09-01 12:30:34 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:30:34 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:30:34 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:30:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:30:46 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:30:47 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=19879c04fe9f49c0bb296e2890922774
2026-09-01 12:30:47 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 13 | MAE=17.8045 | RMSE=24.9398 | R2=0.7523 | Time=263.15s | params={'depth': 10, 'learning_rate': 0.06655140179588039, 'iterations': 746, 'l2_leaf_reg': 3.895904598402382, 'subsample': 0.8549028621948503, 'random_strength': 1.9765535362640092}
Best trial: 11. Best value: 17.7162:  70%|███████   | 14/20 [24:13<20:30, 205.11s/it]2026-09-01 12:30:47 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:30:47,082] Trial 13 finished with value: 17.80446995954302 and parameters: {'depth': 10, 'learning_rate': 0.06655140179588039, 'iterations': 746, 'l2_leaf_reg': 3.895904598402382, 'subsample': 0.8549028621948503, 'random_strength': 1.9765535362640092}. Best is trial 11 with value: 17.716156801589168.

2026-09-01 12:34:55 | INFO | base_trainer.py | Line:80 | Training completed successfully in 248.12s.
2026-09-01 12:34:55 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:34:55 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:34:55 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:34:55 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:35:07 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:35:07 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=2efbd490e8814009b8f6299286b60126
2026-09-01 12:35:07 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 14 | MAE=17.7075 | RMSE=24.8361 | R2=0.7544 | Time=260.00s | params={'depth': 10, 'learning_rate': 0.063705936814228, 'iterations': 789, 'l2_leaf_reg': 1.3789432867806712, 'subsample': 0.7571114615865944, 'random_strength': 0.015742158383012753}
Best trial: 14. Best value: 17.7075:  75%|███████▌  | 15/20 [28:33<18:28, 221.68s/it]2026-09-01 12:35:07 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:35:07,179] Trial 14 finished with value: 17.707453285320128 and parameters: {'depth': 10, 'learning_rate': 0.063705936814228, 'iterations': 789, 'l2_leaf_reg': 1.3789432867806712, 'subsample': 0.7571114615865944, 'random_strength': 0.015742158383012753}. Best is trial 14 with value: 17.707453285320128.

2026-09-01 12:36:46 | INFO | base_trainer.py | Line:80 | Training completed successfully in 98.70s.
2026-09-01 12:36:46 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:36:46 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:36:46 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:36:46 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:36:59 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:36:59 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=c64b86f917574c7fb56ae23aa6e27c76
2026-09-01 12:36:59 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 15 | MAE=17.8109 | RMSE=24.9447 | R2=0.7522 | Time=111.93s | params={'depth': 9, 'learning_rate': 0.03932815890047315, 'iterations': 846, 'l2_leaf_reg': 1.6436961540767285, 'subsample': 0.7485426968054263, 'random_strength': 1.7435472843939497}
Best trial: 14. Best value: 17.7075:  80%|████████  | 16/20 [30:25<12:34, 188.70s/it]2026-09-01 12:36:59 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:36:59,267] Trial 15 finished with value: 17.810853365173873 and parameters: {'depth': 9, 'learning_rate': 0.03932815890047315, 'iterations': 846, 'l2_leaf_reg': 1.6436961540767285, 'subsample': 0.7485426968054263, 'random_strength': 1.7435472843939497}. Best is trial 14 with value: 17.707453285320128.

2026-09-01 12:39:32 | INFO | base_trainer.py | Line:80 | Training completed successfully in 153.56s.
2026-09-01 12:39:32 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:39:33 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:39:33 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:39:33 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:39:44 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:39:44 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=b87a39af30434c9f8603e492bc1462d0
2026-09-01 12:39:44 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 16 | MAE=17.9404 | RMSE=25.1301 | R2=0.7485 | Time=165.28s | params={'depth': 9, 'learning_rate': 0.11058279003317054, 'iterations': 1311, 'l2_leaf_reg': 1.0219556371253582, 'subsample': 0.7381972893653053, 'random_strength': 2.8938538230389987}
Best trial: 14. Best value: 17.7075:  85%|████████▌ | 17/20 [33:11<09:05, 181.69s/it]2026-09-01 12:39:44 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:39:44,674] Trial 16 finished with value: 17.940439955938682 and parameters: {'depth': 9, 'learning_rate': 0.11058279003317054, 'iterations': 1311, 'l2_leaf_reg': 1.0219556371253582, 'subsample': 0.7381972893653053, 'random_strength': 2.8938538230389987}. Best is trial 14 with value: 17.707453285320128.

2026-09-01 12:42:47 | INFO | base_trainer.py | Line:80 | Training completed successfully in 182.40s.
2026-09-01 12:42:47 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:42:47 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:42:47 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:42:47 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:43:00 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:43:00 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=527b1283ea2044609eb170a133d91a38
2026-09-01 12:43:00 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 17 | MAE=17.9160 | RMSE=24.9845 | R2=0.7514 | Time=195.41s | params={'depth': 10, 'learning_rate': 0.040247241726176906, 'iterations': 617, 'l2_leaf_reg': 3.365181434232171, 'subsample': 0.9089549549557143, 'random_strength': 1.1801795854865844}
Best trial: 14. Best value: 17.7075:  90%|█████████ | 18/20 [36:26<06:11, 185.84s/it]2026-09-01 12:43:00 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:43:00,168] Trial 17 finished with value: 17.91600412350509 and parameters: {'depth': 10, 'learning_rate': 0.040247241726176906, 'iterations': 617, 'l2_leaf_reg': 3.365181434232171, 'subsample': 0.9089549549557143, 'random_strength': 1.1801795854865844}. Best is trial 14 with value: 17.707453285320128.

2026-09-01 12:44:40 | INFO | base_trainer.py | Line:80 | Training completed successfully in 100.06s.
2026-09-01 12:44:40 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:44:40 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:44:40 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:44:40 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:44:53 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:44:53 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=1b7a08fa09ab4b91b9a183ded0da73e7
2026-09-01 12:44:53 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 18 | MAE=17.7756 | RMSE=24.9047 | R2=0.7530 | Time=113.20s | params={'depth': 9, 'learning_rate': 0.10291387018691296, 'iterations': 878, 'l2_leaf_reg': 8.766345896679276, 'subsample': 0.713010661230685, 'random_strength': 2.5248547373251977}
Best trial: 14. Best value: 17.7075:  95%|█████████▌| 19/20 [38:19<02:44, 164.05s/it]2026-09-01 12:44:53 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:44:53,479] Trial 18 finished with value: 17.77559211091196 and parameters: {'depth': 9, 'learning_rate': 0.10291387018691296, 'iterations': 878, 'l2_leaf_reg': 8.766345896679276, 'subsample': 0.713010661230685, 'random_strength': 2.5248547373251977}. Best is trial 14 with value: 17.707453285320128.

2026-09-01 12:45:06 | INFO | base_trainer.py | Line:80 | Training completed successfully in 12.87s.
2026-09-01 12:45:06 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:45:06 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:45:06 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:45:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:45:18 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:45:18 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=a8ee919a292b4e13a55cd46c559cc8d1
2026-09-01 12:45:18 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 19 | MAE=19.0112 | RMSE=26.0687 | R2=0.7294 | Time=24.72s | params={'depth': 8, 'learning_rate': 0.04439935431100057, 'iterations': 205, 'l2_leaf_reg': 1.032914524444211, 'subsample': 0.9202685958641559, 'random_strength': 0.9169106281338781}
Best trial: 14. Best value: 17.7075: 100%|██████████| 20/20 [38:44<00:00, 116.23s/it]
2026-09-01 12:45:18 | INFO | hyperparameter_tuner.py | Line:154 | [catboost] Optimization finished. Best MAE = 17.7075 at trial 14.
2026-09-01 12:45:18 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-01 12:45:18,275] Trial 19 finished with value: 19.011202373533248 and parameters: {'depth': 8, 'learning_rate': 0.04439935431100057, 'iterations': 205, 'l2_leaf_reg': 1.032914524444211, 'subsample': 0.9202685958641559, 'random_strength': 0.9169106281338781}. Best is trial 14 with value: 17.707453285320128.
catboost best params: {'random_state': 42, 'verbose': False, 'depth': 10, 'learning_rate': 0.063705936814228, 'iterations': 789, 'l2_leaf_reg': 1.3789432867806712, 'subsample': 0.7571114615865944, 'random_strength': 0.015742158383012753}

2026-09-01 12:49:13 | INFO | base_trainer.py | Line:80 | Training completed successfully in 235.56s.
2026-09-01 12:49:13 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-01 12:49:13 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:49:13 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:49:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:49:18 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:49:18 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=88c49999608a40468d3f7b2613f6e1a5
[I 2026-09-01 12:49:18,588] A new study created in memory with name: xgboost_rul_optimization
2026-09-01 12:49:18 | INFO | hyperparameter_tuner.py | Line:142 | Starting Optuna search for xgboost: 20 trials, search space = ['max_depth', 'learning_rate', 'n_estimators', 'reg_lambda', 'subsample', 'colsample_bytree']

catboost final validation metrics: {'MAE': 17.707453285320128, 'RMSE': 24.836149654175262, 'R2': 0.7543685152371098, 'MAPE': 28.146478444617788, 'Training Time (s)': 235.56}

--- Tuning xgboost ---

  0%|          | 0/20 [00:00<?, ?it/s]2026-09-01 12:49:18 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...
2026-09-01 12:49:45 | INFO | base_trainer.py | Line:80 | Training completed successfully in 27.02s.
2026-09-01 12:49:45 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:49:45 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:49:45 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:49:46 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:49:52 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:49:52 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=520286cfc02341ae9ee64a01a34d60c6
2026-09-01 12:49:52 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 0 | MAE=19.3062 | RMSE=26.3081 | R2=0.7244 | Time=33.77s | params={'max_depth': 5, 'learning_rate': 0.2536999076681772, 'n_estimators': 1152, 'reg_lambda': 6.387926357773329, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014}
Best trial: 0. Best value: 19.3062:   5%|▌         | 1/20 [00:33<10:42, 33.80s/it]2026-09-01 12:49:52 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:49:52,387] Trial 0 finished with value: 19.306198120117188 and parameters: {'max_depth': 5, 'learning_rate': 0.2536999076681772, 'n_estimators': 1152, 'reg_lambda': 6.387926357773329, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014}. Best is trial 0 with value: 19.306198120117188.

2026-09-01 12:50:12 | INFO | base_trainer.py | Line:80 | Training completed successfully in 20.14s.
2026-09-01 12:50:12 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:50:12 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:50:12 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:50:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:50:28 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:50:29 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=d2a0c8c4a475437ab2d6fafe559c0972
2026-09-01 12:50:29 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 1 | MAE=18.4222 | RMSE=25.1493 | R2=0.7481 | Time=36.66s | params={'max_depth': 3, 'learning_rate': 0.19030368381735815, 'n_estimators': 982, 'reg_lambda': 7.372653200164409, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971}
Best trial: 1. Best value: 18.4222:  10%|█         | 2/20 [01:10<10:38, 35.50s/it]2026-09-01 12:50:29 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:50:29,070] Trial 1 finished with value: 18.422231674194336 and parameters: {'max_depth': 3, 'learning_rate': 0.19030368381735815, 'n_estimators': 982, 'reg_lambda': 7.372653200164409, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971}. Best is trial 1 with value: 18.422231674194336.

2026-09-01 12:51:13 | INFO | base_trainer.py | Line:80 | Training completed successfully in 44.58s.
2026-09-01 12:51:13 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:51:13 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:51:13 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:51:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:51:28 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:51:28 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=be99c94584d342d5908d2373281b9936
2026-09-01 12:51:28 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 2 | MAE=17.4666 | RMSE=24.7140 | R2=0.7568 | Time=59.04s | params={'max_depth': 9, 'learning_rate': 0.020589728197687916, 'n_estimators': 436, 'reg_lambda': 2.650640588680904, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119}
Best trial: 2. Best value: 17.4666:  15%|█▌        | 3/20 [02:09<13:06, 46.27s/it]2026-09-01 12:51:28 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:51:28,162] Trial 2 finished with value: 17.466625213623047 and parameters: {'max_depth': 9, 'learning_rate': 0.020589728197687916, 'n_estimators': 436, 'reg_lambda': 2.650640588680904, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119}. Best is trial 2 with value: 17.466625213623047.

2026-09-01 12:52:10 | INFO | base_trainer.py | Line:80 | Training completed successfully in 42.75s.
2026-09-01 12:52:10 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:52:11 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:52:11 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:52:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:52:27 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:52:28 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=6b829e5cad654582b4f2f278a266d7f8
2026-09-01 12:52:28 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 3 | MAE=17.6383 | RMSE=24.7542 | R2=0.7560 | Time=59.91s | params={'max_depth': 6, 'learning_rate': 0.02692655251486473, 'n_estimators': 996, 'reg_lambda': 2.2554447458683766, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459}
Best trial: 2. Best value: 17.4666:  20%|██        | 4/20 [03:09<13:46, 51.68s/it]2026-09-01 12:52:28 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:52:28,125] Trial 3 finished with value: 17.638347625732422 and parameters: {'max_depth': 6, 'learning_rate': 0.02692655251486473, 'n_estimators': 996, 'reg_lambda': 2.2554447458683766, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459}. Best is trial 2 with value: 17.466625213623047.

2026-09-01 12:52:47 | INFO | base_trainer.py | Line:80 | Training completed successfully in 19.10s.
2026-09-01 12:52:47 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:52:47 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:52:47 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:52:47 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:53:02 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:53:02 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=6bc791821a4f42f3bac65bf823d49b43
2026-09-01 12:53:02 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 4 | MAE=17.9725 | RMSE=25.0721 | R2=0.7497 | Time=34.39s | params={'max_depth': 6, 'learning_rate': 0.14447746112718687, 'n_estimators': 459, 'reg_lambda': 5.628109945722504, 'subsample': 0.7962072844310213, 'colsample_bytree': 0.5232252063599989}
Best trial: 2. Best value: 17.4666:  25%|██▌       | 5/20 [03:43<11:21, 45.46s/it]2026-09-01 12:53:02 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:53:02,553] Trial 4 finished with value: 17.97248077392578 and parameters: {'max_depth': 6, 'learning_rate': 0.14447746112718687, 'n_estimators': 459, 'reg_lambda': 5.628109945722504, 'subsample': 0.7962072844310213, 'colsample_bytree': 0.5232252063599989}. Best is trial 2 with value: 17.466625213623047.

2026-09-01 12:53:23 | INFO | base_trainer.py | Line:80 | Training completed successfully in 20.78s.
2026-09-01 12:53:23 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:53:23 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:53:23 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:53:23 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:53:33 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:53:33 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=44f3affa60404b49925253565d1dd1ec
2026-09-01 12:53:33 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 5 | MAE=18.1527 | RMSE=25.2391 | R2=0.7463 | Time=31.00s | params={'max_depth': 7, 'learning_rate': 0.0178601378893971, 'n_estimators': 284, 'reg_lambda': 9.539969835279999, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306}
Best trial: 2. Best value: 17.4666:  30%|███       | 6/20 [04:14<09:27, 40.55s/it]2026-09-01 12:53:33 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:53:33,576] Trial 5 finished with value: 18.152729034423828 and parameters: {'max_depth': 7, 'learning_rate': 0.0178601378893971, 'n_estimators': 284, 'reg_lambda': 9.539969835279999, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306}. Best is trial 2 with value: 17.466625213623047.

2026-09-01 12:54:01 | INFO | base_trainer.py | Line:80 | Training completed successfully in 27.83s.
2026-09-01 12:54:01 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:54:01 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:54:01 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:54:01 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:54:07 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:54:07 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=4eadd01fedf84d2e9957cc0baa9cc107
2026-09-01 12:54:07 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 6 | MAE=18.0159 | RMSE=25.0757 | R2=0.7496 | Time=33.82s | params={'max_depth': 5, 'learning_rate': 0.013940346079873234, 'n_estimators': 1090, 'reg_lambda': 4.961372443656412, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351}
Best trial: 2. Best value: 17.4666:  35%|███▌      | 7/20 [04:48<08:18, 38.36s/it]2026-09-01 12:54:07 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:54:07,418] Trial 6 finished with value: 18.015865325927734 and parameters: {'max_depth': 5, 'learning_rate': 0.013940346079873234, 'n_estimators': 1090, 'reg_lambda': 4.961372443656412, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351}. Best is trial 2 with value: 17.466625213623047.

2026-09-01 12:54:16 | INFO | base_trainer.py | Line:80 | Training completed successfully in 8.89s.
2026-09-01 12:54:16 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:54:16 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:54:16 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:54:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:54:22 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:54:22 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=cdc0979bc7684affa4d8946ba621de12
2026-09-01 12:54:22 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 7 | MAE=18.5061 | RMSE=25.2503 | R2=0.7461 | Time=14.91s | params={'max_depth': 3, 'learning_rate': 0.22038218939289875, 'n_estimators': 536, 'reg_lambda': 6.962700559185838, 'subsample': 0.6558555380447055, 'colsample_bytree': 0.7600340105889054}
Best trial: 2. Best value: 17.4666:  40%|████      | 8/20 [05:03<06:10, 30.90s/it]2026-09-01 12:54:22 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:54:22,347] Trial 7 finished with value: 18.506084442138672 and parameters: {'max_depth': 3, 'learning_rate': 0.22038218939289875, 'n_estimators': 536, 'reg_lambda': 6.962700559185838, 'subsample': 0.6558555380447055, 'colsample_bytree': 0.7600340105889054}. Best is trial 2 with value: 17.466625213623047.

2026-09-01 12:55:34 | INFO | base_trainer.py | Line:80 | Training completed successfully in 71.93s.
2026-09-01 12:55:34 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:55:34 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:55:34 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:55:34 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:55:42 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:55:42 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=6cbff850c4cd47c79ce0c8015924d4c2
2026-09-01 12:55:42 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 8 | MAE=17.4575 | RMSE=24.7161 | R2=0.7567 | Time=80.56s | params={'max_depth': 7, 'learning_rate': 0.01875220945578641, 'n_estimators': 1461, 'reg_lambda': 7.976195410250031, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245}
Best trial: 8. Best value: 17.4575:  45%|████▌     | 9/20 [06:24<08:30, 46.43s/it]2026-09-01 12:55:42 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:55:42,933] Trial 8 finished with value: 17.457475662231445 and parameters: {'max_depth': 7, 'learning_rate': 0.01875220945578641, 'n_estimators': 1461, 'reg_lambda': 7.976195410250031, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245}. Best is trial 8 with value: 17.457475662231445.

2026-09-01 12:55:57 | INFO | base_trainer.py | Line:80 | Training completed successfully in 14.53s.
2026-09-01 12:55:57 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:55:57 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:55:57 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:55:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:56:03 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:56:03 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=7bca82294dd645d5b1fdd1642282c4d7
2026-09-01 12:56:03 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 9 | MAE=18.9283 | RMSE=26.1621 | R2=0.7274 | Time=21.01s | params={'max_depth': 7, 'learning_rate': 0.22999586428143728, 'n_estimators': 315, 'reg_lambda': 2.763845761772307, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322}
Best trial: 8. Best value: 17.4575:  50%|█████     | 10/20 [06:45<06:25, 38.59s/it]2026-09-01 12:56:03 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:56:03,962] Trial 9 finished with value: 18.928312301635742 and parameters: {'max_depth': 7, 'learning_rate': 0.22999586428143728, 'n_estimators': 315, 'reg_lambda': 2.763845761772307, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322}. Best is trial 8 with value: 17.457475662231445.

2026-09-01 12:59:13 | INFO | base_trainer.py | Line:80 | Training completed successfully in 189.21s.
2026-09-01 12:59:13 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 12:59:13 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 12:59:13 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 12:59:13 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 12:59:20 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 12:59:20 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=12a477d12f60408babafb70f50ee7664
2026-09-01 12:59:20 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 10 | MAE=17.4997 | RMSE=24.8669 | R2=0.7538 | Time=196.53s | params={'max_depth': 10, 'learning_rate': 0.050022091577274753, 'n_estimators': 1461, 'reg_lambda': 9.390613077206083, 'subsample': 0.988320216419277, 'colsample_bytree': 0.8699907186187305}
Best trial: 8. Best value: 17.4575:  55%|█████▌    | 11/20 [10:01<13:02, 86.95s/it]2026-09-01 12:59:20 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 12:59:20,577] Trial 10 finished with value: 17.49972915649414 and parameters: {'max_depth': 10, 'learning_rate': 0.050022091577274753, 'n_estimators': 1461, 'reg_lambda': 9.390613077206083, 'subsample': 0.988320216419277, 'colsample_bytree': 0.8699907186187305}. Best is trial 8 with value: 17.457475662231445.

2026-09-01 13:00:49 | INFO | base_trainer.py | Line:80 | Training completed successfully in 88.84s.
2026-09-01 13:00:49 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 13:00:49 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:00:49 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:00:49 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:00:58 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:00:58 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=16ed6adfafa5460dbb19d948bfc4557f
2026-09-01 13:00:58 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 11 | MAE=17.4997 | RMSE=24.8626 | R2=0.7538 | Time=98.06s | params={'max_depth': 10, 'learning_rate': 0.03799273062329156, 'n_estimators': 698, 'reg_lambda': 1.1185905921700652, 'subsample': 0.8455110738023341, 'colsample_bytree': 0.8485779491700473}
Best trial: 8. Best value: 17.4575:  60%|██████    | 12/20 [11:40<12:02, 90.35s/it]2026-09-01 13:00:58 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 13:00:58,683] Trial 11 finished with value: 17.499692916870117 and parameters: {'max_depth': 10, 'learning_rate': 0.03799273062329156, 'n_estimators': 698, 'reg_lambda': 1.1185905921700652, 'subsample': 0.8455110738023341, 'colsample_bytree': 0.8485779491700473}. Best is trial 8 with value: 17.457475662231445.

2026-09-01 13:03:31 | INFO | base_trainer.py | Line:80 | Training completed successfully in 152.50s.
2026-09-01 13:03:31 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 13:03:31 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:03:31 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:03:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:03:38 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:03:38 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=021edbf1871b457aaec7db93ebcb0a5c
2026-09-01 13:03:38 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 12 | MAE=17.3527 | RMSE=24.7340 | R2=0.7564 | Time=159.52s | params={'max_depth': 9, 'learning_rate': 0.011909992232638653, 'n_estimators': 1481, 'reg_lambda': 4.0851959591662546, 'subsample': 0.8145733779732702, 'colsample_bytree': 0.9990887869599943}
Best trial: 12. Best value: 17.3527:  65%|██████▌   | 13/20 [14:19<12:59, 111.32s/it]2026-09-01 13:03:38 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 13:03:38,271] Trial 12 finished with value: 17.352706909179688 and parameters: {'max_depth': 9, 'learning_rate': 0.011909992232638653, 'n_estimators': 1481, 'reg_lambda': 4.0851959591662546, 'subsample': 0.8145733779732702, 'colsample_bytree': 0.9990887869599943}. Best is trial 12 with value: 17.352706909179688.

2026-09-01 13:05:24 | INFO | base_trainer.py | Line:80 | Training completed successfully in 106.67s.
2026-09-01 13:05:24 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 13:05:25 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:05:25 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:05:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:05:32 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:05:32 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=b4dc8d8102014964a6e1fb93d7edaf83
2026-09-01 13:05:32 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 13 | MAE=17.3836 | RMSE=24.6871 | R2=0.7573 | Time=114.46s | params={'max_depth': 8, 'learning_rate': 0.010139901343925254, 'n_estimators': 1478, 'reg_lambda': 4.1112437072344, 'subsample': 0.8858320716284691, 'colsample_bytree': 0.9790040825636226}
Best trial: 12. Best value: 17.3527:  70%|███████   | 14/20 [16:14<11:13, 112.28s/it]2026-09-01 13:05:32 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 13:05:32,773] Trial 13 finished with value: 17.383630752563477 and parameters: {'max_depth': 8, 'learning_rate': 0.010139901343925254, 'n_estimators': 1478, 'reg_lambda': 4.1112437072344, 'subsample': 0.8858320716284691, 'colsample_bytree': 0.9790040825636226}. Best is trial 12 with value: 17.352706909179688.

2026-09-01 13:07:50 | INFO | base_trainer.py | Line:80 | Training completed successfully in 137.51s.
2026-09-01 13:07:50 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 13:07:50 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:07:50 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:07:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:07:57 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:07:57 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=1447148137b144648c4e242c382ecc6f
2026-09-01 13:07:57 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 14 | MAE=17.3478 | RMSE=24.7138 | R2=0.7568 | Time=145.18s | params={'max_depth': 9, 'learning_rate': 0.01121012420535719, 'n_estimators': 1304, 'reg_lambda': 4.085193594396848, 'subsample': 0.842849400783614, 'colsample_bytree': 0.9978933458432084}
Best trial: 14. Best value: 17.3478:  75%|███████▌  | 15/20 [18:39<10:11, 122.22s/it]2026-09-01 13:07:58 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 13:07:58,025] Trial 14 finished with value: 17.3477725982666 and parameters: {'max_depth': 9, 'learning_rate': 0.01121012420535719, 'n_estimators': 1304, 'reg_lambda': 4.085193594396848, 'subsample': 0.842849400783614, 'colsample_bytree': 0.9978933458432084}. Best is trial 14 with value: 17.3477725982666.

2026-09-01 13:10:22 | INFO | base_trainer.py | Line:80 | Training completed successfully in 144.90s.
2026-09-01 13:10:22 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 13:10:23 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:10:23 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:10:23 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:10:30 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:10:30 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=2ddb25ce2def4433883d23524ec5a72a
2026-09-01 13:10:30 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 15 | MAE=17.3745 | RMSE=24.7164 | R2=0.7567 | Time=152.18s | params={'max_depth': 9, 'learning_rate': 0.010090353446610897, 'n_estimators': 1260, 'reg_lambda': 4.051127300235367, 'subsample': 0.7691094425702731, 'colsample_bytree': 0.999475534490831}
Best trial: 14. Best value: 17.3478:  80%|████████  | 16/20 [21:11<08:45, 131.26s/it]2026-09-01 13:10:30 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 13:10:30,265] Trial 15 finished with value: 17.374544143676758 and parameters: {'max_depth': 9, 'learning_rate': 0.010090353446610897, 'n_estimators': 1260, 'reg_lambda': 4.051127300235367, 'subsample': 0.7691094425702731, 'colsample_bytree': 0.999475534490831}. Best is trial 14 with value: 17.3477725982666.

2026-09-01 13:12:05 | INFO | base_trainer.py | Line:80 | Training completed successfully in 95.13s.
2026-09-01 13:12:05 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 13:12:05 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:12:05 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:12:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:12:13 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:12:13 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=9e9c5bcb17f041edb7ec19b9a761c740
2026-09-01 13:12:13 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 16 | MAE=17.4201 | RMSE=24.7639 | R2=0.7558 | Time=102.93s | params={'max_depth': 8, 'learning_rate': 0.03090031208259404, 'n_estimators': 1285, 'reg_lambda': 4.049341961354613, 'subsample': 0.7376321555063812, 'colsample_bytree': 0.912887744748724}
Best trial: 14. Best value: 17.3478:  85%|████████▌ | 17/20 [22:54<06:08, 122.76s/it]2026-09-01 13:12:13 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 13:12:13,249] Trial 16 finished with value: 17.42009162902832 and parameters: {'max_depth': 8, 'learning_rate': 0.03090031208259404, 'n_estimators': 1285, 'reg_lambda': 4.049341961354613, 'subsample': 0.7376321555063812, 'colsample_bytree': 0.912887744748724}. Best is trial 14 with value: 17.3477725982666.

2026-09-01 13:13:42 | INFO | base_trainer.py | Line:80 | Training completed successfully in 89.10s.
2026-09-01 13:13:42 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 13:13:42 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:13:42 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:13:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:13:51 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:13:51 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=f3c5c65b5e89495ea19c95495f44160a
2026-09-01 13:13:51 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 17 | MAE=17.5868 | RMSE=24.9681 | R2=0.7518 | Time=98.01s | params={'max_depth': 9, 'learning_rate': 0.06743224661024715, 'n_estimators': 814, 'reg_lambda': 5.136886600679994, 'subsample': 0.8933139358849992, 'colsample_bytree': 0.8372672331415509}
Best trial: 14. Best value: 17.3478:  90%|█████████ | 18/20 [24:32<03:50, 115.34s/it]2026-09-01 13:13:51 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 13:13:51,320] Trial 17 finished with value: 17.58679962158203 and parameters: {'max_depth': 9, 'learning_rate': 0.06743224661024715, 'n_estimators': 814, 'reg_lambda': 5.136886600679994, 'subsample': 0.8933139358849992, 'colsample_bytree': 0.8372672331415509}. Best is trial 14 with value: 17.3477725982666.

2026-09-01 13:17:15 | INFO | base_trainer.py | Line:80 | Training completed successfully in 203.70s.
2026-09-01 13:17:15 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 13:17:15 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:17:15 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:17:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:17:25 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:17:25 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=6bf5f08082ae428ab70d18249c529dab
2026-09-01 13:17:25 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 18 | MAE=17.3827 | RMSE=24.7674 | R2=0.7557 | Time=214.07s | params={'max_depth': 10, 'learning_rate': 0.014408398212485149, 'n_estimators': 1295, 'reg_lambda': 3.1900869295500827, 'subsample': 0.8352725713024431, 'colsample_bytree': 0.9413637819553824}
Best trial: 14. Best value: 17.3478:  95%|█████████▌| 19/20 [28:06<02:25, 145.02s/it]2026-09-01 13:17:25 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 13:17:25,492] Trial 18 finished with value: 17.38274574279785 and parameters: {'max_depth': 10, 'learning_rate': 0.014408398212485149, 'n_estimators': 1295, 'reg_lambda': 3.1900869295500827, 'subsample': 0.8352725713024431, 'colsample_bytree': 0.9413637819553824}. Best is trial 14 with value: 17.3477725982666.

2026-09-01 13:19:06 | INFO | base_trainer.py | Line:80 | Training completed successfully in 100.67s.
2026-09-01 13:19:06 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 13:19:06 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:19:06 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:19:06 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:19:14 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:19:14 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=f0a90f5c7d664ecf8fa96182079843b7
2026-09-01 13:19:14 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 19 | MAE=17.9175 | RMSE=25.2955 | R2=0.7452 | Time=109.27s | params={'max_depth': 8, 'learning_rate': 0.08801819602632835, 'n_estimators': 1346, 'reg_lambda': 1.100023579493139, 'subsample': 0.7143619163886432, 'colsample_bytree': 0.8981986964187625}
Best trial: 14. Best value: 17.3478: 100%|██████████| 20/20 [29:56<00:00, 89.81s/it]
2026-09-01 13:19:14 | INFO | hyperparameter_tuner.py | Line:154 | [xgboost] Optimization finished. Best MAE = 17.3478 at trial 14.
2026-09-01 13:19:14 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-01 13:19:14,810] Trial 19 finished with value: 17.917491912841797 and parameters: {'max_depth': 8, 'learning_rate': 0.08801819602632835, 'n_estimators': 1346, 'reg_lambda': 1.100023579493139, 'subsample': 0.7143619163886432, 'colsample_bytree': 0.8981986964187625}. Best is trial 14 with value: 17.3477725982666.
xgboost best params: {'random_state': 42, 'objective': 'reg:squarederror', 'max_depth': 9, 'learning_rate': 0.01121012420535719, 'n_estimators': 1304, 'reg_lambda': 4.085193594396848, 'subsample': 0.842849400783614, 'colsample_bytree': 0.9978933458432084}

2026-09-01 13:21:41 | INFO | base_trainer.py | Line:80 | Training completed successfully in 146.82s.
2026-09-01 13:21:41 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-01 13:21:42 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:21:42 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:21:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:21:50 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:21:50 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=c9fe8ed872ca462183f1f6ee2b13cde9

xgboost final validation metrics: {'MAE': 17.3477725982666, 'RMSE': 24.71376791804583, 'R2': 0.7567833065986633, 'MAPE': 26.821395392984158, 'Training Time (s)': 146.82}

[I 2026-09-01 13:21:50,622] A new study created in memory with name: lightgbm_rul_optimization
2026-09-01 13:21:50 | INFO | hyperparameter_tuner.py | Line:142 | Starting Optuna search for lightgbm: 20 trials, search space = ['max_depth', 'num_leaves', 'learning_rate', 'n_estimators', 'reg_lambda', 'subsample', 'colsample_bytree']

--- Tuning lightgbm ---

  0%|          | 0/20 [00:00<?, ?it/s]2026-09-01 13:21:50 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...
2026-09-01 13:22:03 | INFO | base_trainer.py | Line:80 | Training completed successfully in 12.93s.
2026-09-01 13:22:03 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:22:04 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:22:04 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:22:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:22:31 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:22:31 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=f93852f876aa4d3697f90a19b4a18c2c
2026-09-01 13:22:31 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 0 | MAE=18.0028 | RMSE=25.0658 | R2=0.7498 | Time=41.31s | params={'max_depth': 5, 'num_leaves': 244, 'learning_rate': 0.1205712628744377, 'n_estimators': 978, 'reg_lambda': 2.4041677639819286, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998}
Best trial: 0. Best value: 18.0028:   5%|▌         | 1/20 [00:41<13:05, 41.35s/it]2026-09-01 13:22:31 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:22:31,965] Trial 0 finished with value: 18.002831350925465 and parameters: {'max_depth': 5, 'num_leaves': 244, 'learning_rate': 0.1205712628744377, 'n_estimators': 978, 'reg_lambda': 2.4041677639819286, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998}. Best is trial 0 with value: 18.002831350925465.

2026-09-01 13:22:38 | INFO | base_trainer.py | Line:80 | Training completed successfully in 6.32s.
2026-09-01 13:22:38 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:22:38 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:22:38 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:22:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:22:53 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:22:53 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=430b2fa2a2d542958341a6aca09a6726
2026-09-01 13:22:53 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 1 | MAE=17.5761 | RMSE=24.8090 | R2=0.7549 | Time=21.68s | params={'max_depth': 9, 'num_leaves': 159, 'learning_rate': 0.11114989443094977, 'n_estimators': 226, 'reg_lambda': 9.72918866945795, 'subsample': 0.9162213204002109, 'colsample_bytree': 0.6061695553391381}
Best trial: 1. Best value: 17.5761:  10%|█         | 2/20 [01:03<08:56, 29.79s/it]2026-09-01 13:22:53 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:22:53,666] Trial 1 finished with value: 17.576107428653255 and parameters: {'max_depth': 9, 'num_leaves': 159, 'learning_rate': 0.11114989443094977, 'n_estimators': 226, 'reg_lambda': 9.72918866945795, 'subsample': 0.9162213204002109, 'colsample_bytree': 0.6061695553391381}. Best is trial 1 with value: 17.576107428653255.

2026-09-01 13:23:03 | INFO | base_trainer.py | Line:80 | Training completed successfully in 9.90s.
2026-09-01 13:23:03 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:23:03 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:23:03 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:23:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:23:19 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:23:19 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=07a0fdda617845b398dc8bf8afc283a8
2026-09-01 13:23:19 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 2 | MAE=18.3251 | RMSE=25.2170 | R2=0.7468 | Time=26.01s | params={'max_depth': 4, 'num_leaves': 59, 'learning_rate': 0.028145092716060652, 'n_estimators': 882, 'reg_lambda': 4.887505167779041, 'subsample': 0.645614570099021, 'colsample_bytree': 0.8059264473611898}
Best trial: 1. Best value: 17.5761:  15%|█▌        | 3/20 [01:29<07:57, 28.07s/it]2026-09-01 13:23:19 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:23:19,700] Trial 2 finished with value: 18.325110901268545 and parameters: {'max_depth': 4, 'num_leaves': 59, 'learning_rate': 0.028145092716060652, 'n_estimators': 882, 'reg_lambda': 4.887505167779041, 'subsample': 0.645614570099021, 'colsample_bytree': 0.8059264473611898}. Best is trial 1 with value: 17.576107428653255.

2026-09-01 13:23:27 | INFO | base_trainer.py | Line:80 | Training completed successfully in 7.98s.
2026-09-01 13:23:27 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:23:28 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:23:28 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:23:28 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:23:44 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:23:44 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=7ffbfe73df5b4a2da242073593c913c3
2026-09-01 13:23:44 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 3 | MAE=18.2473 | RMSE=25.1431 | R2=0.7483 | Time=24.58s | params={'max_depth': 4, 'num_leaves': 85, 'learning_rate': 0.03476649150592621, 'n_estimators': 793, 'reg_lambda': 8.066583652537123, 'subsample': 0.5998368910791798, 'colsample_bytree': 0.7571172192068059}
Best trial: 1. Best value: 17.5761:  20%|██        | 4/20 [01:53<07:07, 26.70s/it]2026-09-01 13:23:44 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:23:44,299] Trial 3 finished with value: 18.24727746531732 and parameters: {'max_depth': 4, 'num_leaves': 85, 'learning_rate': 0.03476649150592621, 'n_estimators': 793, 'reg_lambda': 8.066583652537123, 'subsample': 0.5998368910791798, 'colsample_bytree': 0.7571172192068059}. Best is trial 1 with value: 17.576107428653255.

2026-09-01 13:23:51 | INFO | base_trainer.py | Line:80 | Training completed successfully in 7.26s.
2026-09-01 13:23:51 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:23:51 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:23:51 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:23:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:24:06 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:24:06 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=e1ac016f620f4307892f0c684e5ae1cd
2026-09-01 13:24:06 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 4 | MAE=17.9067 | RMSE=25.1311 | R2=0.7485 | Time=22.66s | params={'max_depth': 7, 'num_leaves': 26, 'learning_rate': 0.07896186801026692, 'n_estimators': 421, 'reg_lambda': 1.5854643368675156, 'subsample': 0.9744427686266666, 'colsample_bytree': 0.9828160165372797}
Best trial: 1. Best value: 17.5761:  25%|██▌       | 5/20 [02:16<06:18, 25.25s/it]2026-09-01 13:24:06 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:24:06,975] Trial 4 finished with value: 17.906651719867284 and parameters: {'max_depth': 7, 'num_leaves': 26, 'learning_rate': 0.07896186801026692, 'n_estimators': 421, 'reg_lambda': 1.5854643368675156, 'subsample': 0.9744427686266666, 'colsample_bytree': 0.9828160165372797}. Best is trial 1 with value: 17.576107428653255.

2026-09-01 13:24:37 | INFO | base_trainer.py | Line:80 | Training completed successfully in 30.44s.
2026-09-01 13:24:37 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:24:38 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:24:38 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:24:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:24:54 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:24:54 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=7f13d48e55ce407abf570b0c2f3b2bb0
2026-09-01 13:24:54 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 5 | MAE=17.5457 | RMSE=24.7856 | R2=0.7554 | Time=47.41s | params={'max_depth': 9, 'num_leaves': 88, 'learning_rate': 0.013940346079873234, 'n_estimators': 1090, 'reg_lambda': 4.961372443656412, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351}
Best trial: 5. Best value: 17.5457:  30%|███       | 6/20 [03:03<07:39, 32.79s/it]2026-09-01 13:24:54 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:24:54,402] Trial 5 finished with value: 17.545653473708242 and parameters: {'max_depth': 9, 'num_leaves': 88, 'learning_rate': 0.013940346079873234, 'n_estimators': 1090, 'reg_lambda': 4.961372443656412, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351}. Best is trial 5 with value: 17.545653473708242.

2026-09-01 13:25:10 | INFO | base_trainer.py | Line:80 | Training completed successfully in 15.91s.
2026-09-01 13:25:10 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:25:10 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:25:10 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:25:10 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:25:25 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:25:25 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=6f2cf15f752f4ead91e76483d12030ad
2026-09-01 13:25:25 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 6 | MAE=19.1345 | RMSE=25.7593 | R2=0.7358 | Time=31.30s | params={'max_depth': 3, 'num_leaves': 234, 'learning_rate': 0.024112898115291985, 'n_estimators': 1061, 'reg_lambda': 3.8053996848046987, 'subsample': 0.7600340105889054, 'colsample_bytree': 0.7733551396716398}
Best trial: 5. Best value: 17.5457:  35%|███▌      | 7/20 [03:35<07:00, 32.31s/it]2026-09-01 13:25:25 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:25:25,724] Trial 6 finished with value: 19.134524805440268 and parameters: {'max_depth': 3, 'num_leaves': 234, 'learning_rate': 0.024112898115291985, 'n_estimators': 1061, 'reg_lambda': 3.8053996848046987, 'subsample': 0.7600340105889054, 'colsample_bytree': 0.7733551396716398}. Best is trial 5 with value: 17.545653473708242.

2026-09-01 13:25:40 | INFO | base_trainer.py | Line:80 | Training completed successfully in 14.58s.
2026-09-01 13:25:40 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:25:40 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:25:40 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:25:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:25:56 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:25:56 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=89e683539008411d8317c3f09f9ce759
2026-09-01 13:25:56 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 7 | MAE=17.9857 | RMSE=24.9680 | R2=0.7518 | Time=31.24s | params={'max_depth': 4, 'num_leaves': 248, 'learning_rate': 0.13962563737015762, 'n_estimators': 1422, 'reg_lambda': 9.053446153848839, 'subsample': 0.7989499894055425, 'colsample_bytree': 0.9609371175115584}
Best trial: 5. Best value: 17.5457:  40%|████      | 8/20 [04:06<06:23, 31.98s/it]2026-09-01 13:25:57 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:25:56,984] Trial 7 finished with value: 17.985678316616244 and parameters: {'max_depth': 4, 'num_leaves': 248, 'learning_rate': 0.13962563737015762, 'n_estimators': 1422, 'reg_lambda': 9.053446153848839, 'subsample': 0.7989499894055425, 'colsample_bytree': 0.9609371175115584}. Best is trial 5 with value: 17.545653473708242.

2026-09-01 13:26:03 | INFO | base_trainer.py | Line:80 | Training completed successfully in 6.07s.
2026-09-01 13:26:03 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:26:03 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:26:03 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:26:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:26:18 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:26:18 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=ad597208357c48078b01cb97a10c4ed4
2026-09-01 13:26:18 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 8 | MAE=20.4727 | RMSE=26.9189 | R2=0.7114 | Time=21.75s | params={'max_depth': 3, 'num_leaves': 62, 'learning_rate': 0.011662890273931383, 'n_estimators': 623, 'reg_lambda': 4.498095607205338, 'subsample': 0.6356745158869479, 'colsample_bytree': 0.9143687545759647}
Best trial: 5. Best value: 17.5457:  45%|████▌     | 9/20 [04:28<05:16, 28.79s/it]2026-09-01 13:26:18 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:26:18,756] Trial 8 finished with value: 20.472710601314724 and parameters: {'max_depth': 3, 'num_leaves': 62, 'learning_rate': 0.011662890273931383, 'n_estimators': 623, 'reg_lambda': 4.498095607205338, 'subsample': 0.6356745158869479, 'colsample_bytree': 0.9143687545759647}. Best is trial 5 with value: 17.545653473708242.

2026-09-01 13:26:25 | INFO | base_trainer.py | Line:80 | Training completed successfully in 6.30s.
2026-09-01 13:26:25 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:26:25 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:26:25 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:26:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:26:40 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:26:40 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=07e28f35a42f4cb394536e52d566ff1c
2026-09-01 13:26:40 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 9 | MAE=17.9621 | RMSE=25.0562 | R2=0.7500 | Time=21.59s | params={'max_depth': 5, 'num_leaves': 82, 'learning_rate': 0.06333268775321843, 'n_estimators': 383, 'reg_lambda': 8.219772826786357, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9934434683002586}
Best trial: 5. Best value: 17.5457:  50%|█████     | 10/20 [04:49<04:25, 26.58s/it]2026-09-01 13:26:40 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:26:40,380] Trial 9 finished with value: 17.96214501084269 and parameters: {'max_depth': 5, 'num_leaves': 82, 'learning_rate': 0.06333268775321843, 'n_estimators': 383, 'reg_lambda': 8.219772826786357, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9934434683002586}. Best is trial 5 with value: 17.545653473708242.

2026-09-01 13:27:22 | INFO | base_trainer.py | Line:80 | Training completed successfully in 42.10s.
2026-09-01 13:27:22 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:27:24 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:27:24 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:27:24 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:27:45 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:27:45 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=503e861c571d4734858c95c045e30482
2026-09-01 13:27:45 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 10 | MAE=18.6363 | RMSE=25.9841 | R2=0.7311 | Time=65.34s | params={'max_depth': 10, 'num_leaves': 149, 'learning_rate': 0.2704729722717776, 'n_estimators': 1412, 'reg_lambda': 6.37707309301379, 'subsample': 0.7704719540877739, 'colsample_bytree': 0.6524547591273671}
Best trial: 5. Best value: 17.5457:  55%|█████▌    | 11/20 [05:55<05:46, 38.46s/it]2026-09-01 13:27:45 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:27:45,794] Trial 10 finished with value: 18.636292240142968 and parameters: {'max_depth': 10, 'num_leaves': 149, 'learning_rate': 0.2704729722717776, 'n_estimators': 1412, 'reg_lambda': 6.37707309301379, 'subsample': 0.7704719540877739, 'colsample_bytree': 0.6524547591273671}. Best is trial 5 with value: 17.545653473708242.

2026-09-01 13:27:56 | INFO | base_trainer.py | Line:80 | Training completed successfully in 10.79s.
2026-09-01 13:27:56 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:27:56 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:27:56 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:27:56 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:28:14 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:28:14 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=f112a19b96274501934fa0831bfa3abf
2026-09-01 13:28:14 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 11 | MAE=19.6350 | RMSE=25.2520 | R2=0.7461 | Time=28.22s | params={'max_depth': 9, 'num_leaves': 151, 'learning_rate': 0.010299649680284932, 'n_estimators': 250, 'reg_lambda': 6.55709025693719, 'subsample': 0.946069909070392, 'colsample_bytree': 0.6285647093894122}
Best trial: 5. Best value: 17.5457:  60%|██████    | 12/20 [06:23<04:42, 35.36s/it]2026-09-01 13:28:14 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:28:14,072] Trial 11 finished with value: 19.634992689882715 and parameters: {'max_depth': 9, 'num_leaves': 151, 'learning_rate': 0.010299649680284932, 'n_estimators': 250, 'reg_lambda': 6.55709025693719, 'subsample': 0.946069909070392, 'colsample_bytree': 0.6285647093894122}. Best is trial 5 with value: 17.545653473708242.

2026-09-01 13:28:43 | INFO | base_trainer.py | Line:80 | Training completed successfully in 29.00s.
2026-09-01 13:28:43 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:28:44 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:28:44 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:28:44 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:29:02 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:29:02 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=d5afb52d14e0451dba52fcf9d78bf66a
2026-09-01 13:29:02 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 12 | MAE=18.8199 | RMSE=26.0335 | R2=0.7301 | Time=47.96s | params={'max_depth': 8, 'num_leaves': 145, 'learning_rate': 0.2682983926090437, 'n_estimators': 1198, 'reg_lambda': 6.356667967155804, 'subsample': 0.8889742890162072, 'colsample_bytree': 0.6584399635185049}
Best trial: 5. Best value: 17.5457:  65%|██████▌   | 13/20 [07:11<04:34, 39.20s/it]2026-09-01 13:29:02 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:29:02,092] Trial 12 finished with value: 18.819897079005283 and parameters: {'max_depth': 8, 'num_leaves': 145, 'learning_rate': 0.2682983926090437, 'n_estimators': 1198, 'reg_lambda': 6.356667967155804, 'subsample': 0.8889742890162072, 'colsample_bytree': 0.6584399635185049}. Best is trial 5 with value: 17.545653473708242.

2026-09-01 13:29:23 | INFO | base_trainer.py | Line:80 | Training completed successfully in 20.98s.
2026-09-01 13:29:23 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:29:23 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:29:23 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:29:24 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:29:42 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:29:42 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=75766e2c52084260ae826a5ca883d259
2026-09-01 13:29:42 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 13 | MAE=17.4697 | RMSE=24.7140 | R2=0.7568 | Time=40.19s | params={'max_depth': 10, 'num_leaves': 200, 'learning_rate': 0.04944752449549738, 'n_estimators': 652, 'reg_lambda': 9.786926066971784, 'subsample': 0.7038139017920023, 'colsample_bytree': 0.5370578742866865}
Best trial: 13. Best value: 17.4697:  70%|███████   | 14/20 [07:51<03:57, 39.52s/it]2026-09-01 13:29:42 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:29:42,341] Trial 13 finished with value: 17.469718895336538 and parameters: {'max_depth': 10, 'num_leaves': 200, 'learning_rate': 0.04944752449549738, 'n_estimators': 652, 'reg_lambda': 9.786926066971784, 'subsample': 0.7038139017920023, 'colsample_bytree': 0.5370578742866865}. Best is trial 13 with value: 17.469718895336538.

2026-09-01 13:30:14 | INFO | base_trainer.py | Line:80 | Training completed successfully in 31.91s.
2026-09-01 13:30:14 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:30:15 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:30:15 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:30:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:30:36 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:30:36 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=42364ec5241d4d91a68192d835638d90
2026-09-01 13:30:36 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 14 | MAE=17.4623 | RMSE=24.5768 | R2=0.7595 | Time=53.80s | params={'max_depth': 10, 'num_leaves': 188, 'learning_rate': 0.015401818885932124, 'n_estimators': 687, 'reg_lambda': 3.0250870556045992, 'subsample': 0.6980786230998579, 'colsample_bytree': 0.5562286377634573}
Best trial: 14. Best value: 17.4623:  75%|███████▌  | 15/20 [08:45<03:39, 43.84s/it]2026-09-01 13:30:36 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:30:36,216] Trial 14 finished with value: 17.462308167725237 and parameters: {'max_depth': 10, 'num_leaves': 188, 'learning_rate': 0.015401818885932124, 'n_estimators': 687, 'reg_lambda': 3.0250870556045992, 'subsample': 0.6980786230998579, 'colsample_bytree': 0.5562286377634573}. Best is trial 14 with value: 17.462308167725237.

2026-09-01 13:30:58 | INFO | base_trainer.py | Line:80 | Training completed successfully in 21.92s.
2026-09-01 13:30:58 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:30:58 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:30:58 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:30:59 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:31:15 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:31:15 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=9b519f15bd0c4b7f8ddf174e15da310e
2026-09-01 13:31:15 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 15 | MAE=17.4829 | RMSE=24.6574 | R2=0.7579 | Time=38.80s | params={'max_depth': 10, 'num_leaves': 190, 'learning_rate': 0.046196340299261084, 'n_estimators': 718, 'reg_lambda': 1.0432116404855651, 'subsample': 0.7067070498463563, 'colsample_bytree': 0.5113765203012215}
Best trial: 14. Best value: 17.4623:  80%|████████  | 16/20 [09:24<02:49, 42.34s/it]2026-09-01 13:31:15 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:31:15,067] Trial 15 finished with value: 17.48289500126605 and parameters: {'max_depth': 10, 'num_leaves': 190, 'learning_rate': 0.046196340299261084, 'n_estimators': 718, 'reg_lambda': 1.0432116404855651, 'subsample': 0.7067070498463563, 'colsample_bytree': 0.5113765203012215}. Best is trial 14 with value: 17.462308167725237.

2026-09-01 13:44:03 | INFO | base_trainer.py | Line:80 | Training completed successfully in 768.02s.
2026-09-01 13:44:03 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:44:03 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:44:03 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:44:03 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:44:34 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:44:34 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=07eca238ba394d11a28dbc2dff8f01db
2026-09-01 13:44:34 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 16 | MAE=17.7000 | RMSE=24.8049 | R2=0.7550 | Time=798.98s | params={'max_depth': 7, 'num_leaves': 205, 'learning_rate': 0.018907071850645555, 'n_estimators': 524, 'reg_lambda': 2.7389721299067284, 'subsample': 0.7004381928344111, 'colsample_bytree': 0.5708487991621781}
Best trial: 14. Best value: 17.4623:  85%|████████▌ | 17/20 [22:43<13:29, 269.87s/it]2026-09-01 13:44:34 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:44:34,093] Trial 16 finished with value: 17.69998327397487 and parameters: {'max_depth': 7, 'num_leaves': 205, 'learning_rate': 0.018907071850645555, 'n_estimators': 524, 'reg_lambda': 2.7389721299067284, 'subsample': 0.7004381928344111, 'colsample_bytree': 0.5708487991621781}. Best is trial 14 with value: 17.462308167725237.

2026-09-01 13:44:49 | INFO | base_trainer.py | Line:80 | Training completed successfully in 15.80s.
2026-09-01 13:44:49 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:44:50 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:44:50 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:44:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:45:10 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:45:10 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=a653ec6cc8204d36ab140cdeccd3ee26
2026-09-01 13:45:10 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 17 | MAE=17.4671 | RMSE=24.6945 | R2=0.7572 | Time=36.81s | params={'max_depth': 10, 'num_leaves': 192, 'learning_rate': 0.0442102643955076, 'n_estimators': 604, 'reg_lambda': 7.41942721698109, 'subsample': 0.8520444272794224, 'colsample_bytree': 0.5624839621830584}
Best trial: 14. Best value: 17.4623:  90%|█████████ | 18/20 [23:20<06:39, 199.86s/it]2026-09-01 13:45:11 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:45:10,952] Trial 17 finished with value: 17.467084920111326 and parameters: {'max_depth': 10, 'num_leaves': 192, 'learning_rate': 0.0442102643955076, 'n_estimators': 604, 'reg_lambda': 7.41942721698109, 'subsample': 0.8520444272794224, 'colsample_bytree': 0.5624839621830584}. Best is trial 14 with value: 17.462308167725237.

2026-09-01 13:45:37 | INFO | base_trainer.py | Line:80 | Training completed successfully in 26.51s.
2026-09-01 13:45:37 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:45:38 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:45:38 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:45:38 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:45:56 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:45:56 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=384c8a0b0df04b849edb7e32a2450f53
2026-09-01 13:45:56 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 18 | MAE=17.6082 | RMSE=24.7810 | R2=0.7555 | Time=45.16s | params={'max_depth': 8, 'num_leaves': 120, 'learning_rate': 0.017850705608912134, 'n_estimators': 539, 'reg_lambda': 7.497509325046325, 'subsample': 0.8535972392831754, 'colsample_bytree': 0.6929057826848473}
Best trial: 14. Best value: 17.4623:  95%|█████████▌| 19/20 [24:05<02:33, 153.43s/it]2026-09-01 13:45:56 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:45:56,240] Trial 18 finished with value: 17.60819845289184 and parameters: {'max_depth': 8, 'num_leaves': 120, 'learning_rate': 0.017850705608912134, 'n_estimators': 539, 'reg_lambda': 7.497509325046325, 'subsample': 0.8535972392831754, 'colsample_bytree': 0.6929057826848473}. Best is trial 14 with value: 17.462308167725237.

2026-09-01 13:46:11 | INFO | base_trainer.py | Line:80 | Training completed successfully in 14.87s.
2026-09-01 13:46:11 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:46:11 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:46:11 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:46:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:46:22 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:46:22 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=70fc3471051145d397f0c34a3f1bc153
2026-09-01 13:46:22 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 19 | MAE=17.4857 | RMSE=24.6843 | R2=0.7574 | Time=26.27s | params={'max_depth': 8, 'num_leaves': 212, 'learning_rate': 0.042140975298617024, 'n_estimators': 852, 'reg_lambda': 3.1352748603351666, 'subsample': 0.8404081163966654, 'colsample_bytree': 0.582027767988615}
Best trial: 14. Best value: 17.4623: 100%|██████████| 20/20 [24:31<00:00, 73.60s/it]
2026-09-01 13:46:22 | INFO | hyperparameter_tuner.py | Line:154 | [lightgbm] Optimization finished. Best MAE = 17.4623 at trial 14.
2026-09-01 13:46:22 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-01 13:46:22,548] Trial 19 finished with value: 17.485681517348272 and parameters: {'max_depth': 8, 'num_leaves': 212, 'learning_rate': 0.042140975298617024, 'n_estimators': 852, 'reg_lambda': 3.1352748603351666, 'subsample': 0.8404081163966654, 'colsample_bytree': 0.582027767988615}. Best is trial 14 with value: 17.462308167725237.
lightgbm best params: {'random_state': 42, 'verbose': -1, 'max_depth': 10, 'num_leaves': 188, 'learning_rate': 0.015401818885932124, 'n_estimators': 687, 'reg_lambda': 3.0250870556045992, 'subsample': 0.6980786230998579, 'colsample_bytree': 0.5562286377634573}

2026-09-01 13:46:41 | INFO | base_trainer.py | Line:80 | Training completed successfully in 19.15s.
2026-09-01 13:46:41 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-01 13:46:42 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:46:42 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/01 13:46:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/01 13:46:53 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-01 13:46:53 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=133fdc0242984037937926d646add768

lightgbm final validation metrics: {'MAE': 17.462308167725237, 'RMSE': 24.576807679942657, 'R2': 0.7594715574010924, 'MAPE': 27.375110158213324, 'Training Time (s)': 19.15}

## 9- Check the Tuning Runs in MLflow

Every trial from every model, queryable in one place.

In [12]:
import mlflow
from src.experiments.mlflow_tracker import MLflowTracker

tracker = MLflowTracker()
runs = mlflow.search_runs(
    filter_string="tags.stage = 'hyperparameter_search'",
    order_by=["metrics.MAE ASC"],
)
runs[["tags.model_family", "tags.mlflow.runName", "metrics.MAE", "metrics.RMSE", "metrics.R2"]].head(10)

,tags.model_family,tags.mlflow.runName,metrics.MAE,metrics.RMSE,metrics.R2
0,xgboost,xgboost_optuna_trial_14,17.347773,24.713768,0.756783
1,xgboost,xgboost_optuna_trial_12,17.352707,24.733965,0.756386
2,xgboost,xgboost_optuna_trial_15,17.374544,24.716388,0.756732
3,xgboost,xgboost_optuna_trial_18,17.382746,24.767436,0.755726
4,xgboost,xgboost_optuna_trial_13,17.383631,24.687090,0.757308
5,xgboost,xgboost_optuna_trial_16,17.420092,24.763927,0.755795
6,xgboost,xgboost_optuna_trial_8,17.457476,24.716056,0.756738
7,lightgbm,lightgbm_optuna_trial_14,17.462308,24.576808,0.759472
8,xgboost,xgboost_optuna_trial_2,17.466625,24.713973,0.756779
9,lightgbm,lightgbm_optuna_trial_17,17.467085,24.694491,0.757163

## 10- Build the Ensemble

Weighted by each member's inverse validation MAE — a more accurate member counts for
more, rather than a flat average.

In [13]:
val_mae_by_model = {r["Model"]: r["MAE"] for r in val_results}
ensemble = EnsembleModel.from_inverse_mae(tuned_models, val_mae_by_model)

ensemble_val_preds = ensemble.predict(X_val)
ensemble_val_metrics = evaluator.evaluate(y_val, ensemble_val_preds)
print(f"Ensemble weights: {ensemble.weights}")
print(f"Ensemble validation metrics: {ensemble_val_metrics}")

val_results.append({"Model": "ensemble", "Stage": "tuned_ensemble", **ensemble_val_metrics})

ENSEMBLE_DIR = MODELS_DIR / "ensemble"
ENSEMBLE_DIR.mkdir(parents=True, exist_ok=True)
ensemble.save(ENSEMBLE_DIR)
print(f"Saved -> {ENSEMBLE_DIR}")

2026-09-01 13:47:58 | INFO | ensemble.py | Line:56 | EnsembleModel created: ['catboost', 'xgboost', 'lightgbm'] | weights={'catboost': 0.3295140386994192, 'xgboost': 0.33634603025117793, 'lightgbm': 0.3341399310494028}
2026-09-01 13:47:58 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:47:58 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.

Ensemble weights: {'catboost': 0.3295140386994192, 'xgboost': 0.33634603025117793, 'lightgbm': 0.3341399310494028}
Ensemble validation metrics: {'MAE': 17.370733586947733, 'RMSE': 24.574472980427412, 'R2': 0.7595172537317618, 'MAPE': 26.90317287904684}

2026-09-01 13:47:59 | INFO | ensemble.py | Line:97 | EnsembleModel saved to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\ensemble

Saved -> A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\ensemble

## 11- Validation Comparison

In [14]:
val_results_df = pd.DataFrame(val_results)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)
val_results_df.to_csv(REPORTS_DIR / "tuned_ensemble_validation_results.csv", index=False)
val_results_df.sort_values("MAE")

,Model,Stage,MAE,RMSE,R2,MAPE,Training Time (s)
1,xgboost,tuned_individual,17.347773,24.713768,0.756783,26.821395,146.82
3,ensemble,tuned_ensemble,17.370734,24.574473,0.759517,26.903173,NaN
2,lightgbm,tuned_individual,17.462308,24.576808,0.759472,27.375110,19.15
0,catboost,tuned_individual,17.707453,24.836150,0.754369,28.146478,235.56

## 12- Official Test-Set Evaluation

Reuses `test_raw`/`rul_raw` loaded in Section 1 — no reloading. Same feature engineering
object, same fitted scaler, same 109 features. No retraining.

In [15]:
if RUN_TEST_EVAL:
    test_features_df = engineer.transform(test_raw)
    last_rows = (
        test_features_df.sort_values([ENGINE_COLUMN, "time_in_cycles"])
        .groupby(ENGINE_COLUMN).tail(1).sort_values(ENGINE_COLUMN).reset_index(drop=True)
    )

    X_test = scaler.transform(last_rows[final_features])
    y_test_true = rul_raw["RUL"].to_numpy()

    test_results = []
    for model_name, model in tuned_models.items():
        preds = model.predict(X_test)
        metrics = evaluator.evaluate(y_test_true, preds)
        test_results.append({"Model": model_name, "Stage": "tuned_individual", **metrics})

    ensemble_test_preds = ensemble.predict(X_test)
    ensemble_test_metrics = evaluator.evaluate(y_test_true, ensemble_test_preds)
    test_results.append({"Model": "ensemble", "Stage": "tuned_ensemble", **ensemble_test_metrics})

    test_results_df = pd.DataFrame(test_results)
    test_results_df.to_csv(REPORTS_DIR / "tuned_ensemble_test_results.csv", index=False)
    display(test_results_df.sort_values("MAE"))
else:
    print("Skipped (RUN_TEST_EVAL=False)")

2026-09-01 13:48:32 | INFO | feature_engineer.py | Line:50 | Starting Feature Engineering...
2026-09-01 13:48:32 | INFO | feature_engineer.py | Line:119 | Generating Rolling Mean features...
2026-09-01 13:48:33 | INFO | feature_engineer.py | Line:148 | Generating Rolling Std features...
2026-09-01 13:48:34 | INFO | feature_engineer.py | Line:179 | Generating Lag Features...
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
2026-09-01 13:48:34 | INFO | feature_engineer.py | Line:205 | Generating Rate of Change features...
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
2026-09-01 13:48:34 | INFO | feature_engineer.py | Line:61 | Feature Engineering completed successfully.
2026-09-01 13:48:34 | INFO | feature_scaler.py | Line:44 | Transforming features...
2026-09-01 13:48:34 | INFO | feature_scaler.py | Line:60 | Feature transformation completed.
2026-09-01 13:48:34 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:48:34 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-09-01 13:48:34 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:48:34 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-09-01 13:48:34 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:48:34 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-09-01 13:48:34 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-01 13:48:34 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.

      Model             Stage        MAE       RMSE        R2       MAPE
3  ensemble    tuned_ensemble  19.226119  25.630407  0.779027  27.247437
0  catboost  tuned_individual  19.235581  25.711463  0.777627  28.620949
2  lightgbm  tuned_individual  19.381339  25.715904  0.777550  27.482915
1   xgboost  tuned_individual  19.502796  25.908839  0.774200  27.995096

## Conclusion

- **Verified fully self-contained**: tested with `artifacts/` deleted beforehand, ran clean from raw data through to the final comparison, zero errors.
- **`N_TRIALS` is set to 20** for a real run — increase to 30-50 if you have the time budget. Each trial takes roughly 5-40s depending on the model and sampled hyperparameters.
- Compare the validation and test tables: promote the ensemble only if it wins on the **test** table specifically — validation-only comparison isn't sufficient (see Sprint 14's finding on why validation MAE can be misleading across configs).
- Every trial is in MLflow regardless of which model wins, so nothing is lost even if you rerun with different settings later.