# Regime-Aware Normalization + Tuned Multi-Model Ensemble

## Goal

FD004 has **6 operating conditions** (combinations of altitude, speed, throttle — the 3
operational settings). The same sensor produces different "normal" readings depending on
which condition an engine is in — not because of degradation, but because of the operating
condition itself. A single global `StandardScaler` conflates that condition-driven
variation with real degradation signal, adding noise the model has to fight through.

**This was tested, not just theorized.** A controlled A/B experiment
(`regime_normalization_experiment.py`) held CatBoost's hyperparameters completely fixed
and only toggled regime-aware normalization on/off. Result: every metric improved, on
both validation and the official test set:

| Stage | Metric | Baseline | Regime-Normalized |
|---|---|---:|---:|
| Validation | MAE | 18.140 | **17.266** |
| Test | MAE | 19.530 | **19.307** |

This notebook goes further: rather than reusing old hyperparameters (tuned for the old,
globally-scaled features), **every model is re-tuned from scratch** against the new
regime-normalized feature representation, then a fresh ensemble is built from the results.

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path().resolve().parent
sys.path.append(str(PROJECT_ROOT))
print(PROJECT_ROOT)

A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL

In [2]:
N_TRIALS = 20  # per model -- increase for a real search
N_REGIMES = 6  # FD004 has 6 known operating conditions
RUN_TEST_EVAL = True

In [3]:
import json
import joblib
import pandas as pd

from src.config.config import (
    TRAIN_DATA_PATH, TEST_DATA_PATH, RUL_DATA_PATH,
    MODELS_DIR, REPORTS_DIR, SCALERS_DIR,
    VALIDATION_SIZE, RANDOM_STATE, DEFAULT_RUL_CAP,
    ROLLING_WINDOW, LAGS, ENGINE_COLUMN, TARGET_COLUMN,
)
from src.utils.constant import SENSOR_COLUMNS
from src.data.loader import DataLoader
from src.data.validator import DataValidator
from src.preprocessing.rul_generator import RULGenerator
from src.preprocessing.feature_engineer import FeatureEngineer
from src.preprocessing.data_splitter import DataSplitter
from src.preprocessing.feature_scaler import FeatureScaler
from src.preprocessing.regime_normalizer import RegimeNormalizer
from src.explainability.feature_selector import FeatureCategorySelector
from src.explainability.feature_reducer import FeatureReducer
from src.optimization.hyperparameter_tuner import ModelTuner
from src.models.model_factory import ModelFactory
from src.models.base_trainer import BaseTrainer
from src.models.ensemble import EnsembleModel
from src.evaluation.evaluator import RegressionEvaluator

a:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1- Load Raw Data & Validate

In [4]:
loader = DataLoader(train_path=TRAIN_DATA_PATH, test_path=TEST_DATA_PATH, rul_path=RUL_DATA_PATH)
train_raw = loader.load_train()
test_raw = loader.load_test()
rul_raw = loader.load_rul()

print(DataValidator(train_raw, test_raw, rul_raw).validate_all())
print(f"train_FD004: {train_raw.shape}  test_FD004: {test_raw.shape}")

2026-09-03 14:32:22 | INFO | loader.py | Line:18 | Reading train_FD004.txt
2026-09-03 14:32:24 | INFO | loader.py | Line:21 | train_FD004.txt Loaded Successfully
2026-09-03 14:32:24 | INFO | loader.py | Line:18 | Reading test_FD004.txt
2026-09-03 14:32:25 | INFO | loader.py | Line:21 | test_FD004.txt Loaded Successfully
2026-09-03 14:32:25 | INFO | loader.py | Line:18 | Reading RUL_FD004.txt
2026-09-03 14:32:25 | INFO | loader.py | Line:21 | RUL_FD004.txt Loaded Successfully
2026-09-03 14:32:25 | INFO | validator.py | Line:40 | Validating training dataset...
2026-09-03 14:32:25 | INFO | validator.py | Line:50 | Validating testing dataset...
2026-09-03 14:32:25 | INFO | validator.py | Line:60 | Validating RUL dataset...

{'train': {'valid': True, 'errors': [], 'warnings': []}, 'test': {'valid': True, 'errors': [], 'warnings': []}, 'rul': {'valid': True, 'errors': [], 'warnings': ['Duplicate rows found.']}}
train_FD004: (61249, 26)  test_FD004: (41214, 26)

## 2- Generate RUL

In [5]:
train_with_rul = RULGenerator(train_raw).generate(cap=DEFAULT_RUL_CAP)
print(f"cap={DEFAULT_RUL_CAP}  RUL range: [{train_with_rul[TARGET_COLUMN].min()}, {train_with_rul[TARGET_COLUMN].max()}]")

2026-09-03 14:32:28 | INFO | rul_generator.py | Line:82 | Generating Remaining Useful Life (RUL)...
2026-09-03 14:32:28 | INFO | rul_generator.py | Line:92 | Applying RUL cap = 150
2026-09-03 14:32:28 | INFO | rul_generator.py | Line:96 | RUL generated successfully.

cap=150  RUL range: [0, 150]

## 3- Split by Engine *Before* Feature Engineering

Different from the non-regime-aware pipeline, and required here: `RegimeNormalizer`'s
K-Means and per-regime scalers must only ever be fit on training engines. Splitting
before feature engineering (rather than after) guarantees that, without changing the
correctness of the rolling/lag features — those are computed per-engine regardless of
which rows end up in which split.

In [6]:
splitter = DataSplitter(test_size=VALIDATION_SIZE, engine_column=ENGINE_COLUMN, random_state=RANDOM_STATE)
train_split, val_split = splitter.split(train_with_rul)

print(f"Train: {train_split[ENGINE_COLUMN].nunique()} engines ({train_split.shape[0]} rows)")
print(f"Val  : {val_split[ENGINE_COLUMN].nunique()} engines ({val_split.shape[0]} rows)")

2026-09-03 14:32:30 | INFO | data_splitter.py | Line:35 | Starting engine-based train/validation split...
2026-09-03 14:32:31 | INFO | data_splitter.py | Line:67 | Train Engines: 199 | Validation Engines: 50
2026-09-03 14:32:31 | INFO | data_splitter.py | Line:72 | Data splitting completed successfully.

Train: 199 engines (49294 rows)
Val  : 50 engines (11955 rows)

## 4- Regime-Aware Normalization

K-Means on the (scaled) operational settings detects the 6 operating regimes, then a
separate `StandardScaler` is fit per regime for the sensor columns. Fit on training
engines only; validation and test get `.transform()` (regime *prediction*, never a new
fit) — same leakage discipline as every other preprocessing step in this project.

In [8]:
regime_normalizer = RegimeNormalizer(n_regimes=N_REGIMES, sensor_columns=SENSOR_COLUMNS, random_state=RANDOM_STATE)

train_split = regime_normalizer.fit(train_split).transform(train_split)
val_split = regime_normalizer.transform(val_split)
test_raw = regime_normalizer.transform(test_raw)

print(f"Regime distribution (train): {train_split['regime'].value_counts().sort_index().to_dict()}")

MODELS_DIR.mkdir(parents=True, exist_ok=True)
regime_normalizer.save(MODELS_DIR / "regime_normalizer.pkl")

2026-09-03 14:59:50 | INFO | regime_normalizer.py | Line:83 | Detected regime row counts (train): {0: 7375, 1: 7447, 2: 7371, 3: 7307, 4: 7385, 5: 12409}
2026-09-03 14:59:50 | INFO | regime_normalizer.py | Line:134 | RegimeNormalizer saved to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\regime_normalizer.pkl

Regime distribution (train): {0: 7375, 1: 7447, 2: 7371, 3: 7307, 4: 7385, 5: 12409}

## 5- Feature Engineering (on Regime-Normalized Sensor Values)

In [9]:
engineer = FeatureEngineer(sensor_columns=SENSOR_COLUMNS, rolling_window=ROLLING_WINDOW, lags=LAGS)
train_features = engineer.transform(train_split)
val_features = engineer.transform(val_split)
print(f"Engineered: {train_features.shape[1]} columns")

2026-09-03 15:14:05 | INFO | feature_engineer.py | Line:50 | Starting Feature Engineering...
2026-09-03 15:14:05 | INFO | feature_engineer.py | Line:119 | Generating Rolling Mean features...
2026-09-03 15:14:06 | INFO | feature_engineer.py | Line:148 | Generating Rolling Std features...
2026-09-03 15:14:08 | INFO | feature_engineer.py | Line:179 | Generating Lag Features...
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
2026-09-03 15:14:08 | INFO | feature_engineer.py | Line:205 | Generating Rate of Change features...
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
2026-09-03 15:14:08 | INFO | feature_engineer.py | Line:61 | Feature Engineering completed successfully.
2026-09-03 15:14:08 | INFO | feature_engineer.py | Line:50 | Starting Feature Engineering...
2026-09-03 15:14:08 | INFO | feature_engineer.py | Line:119 | Generating Rolling Mean features...
2026-09-03 15:14:09 | INFO | feature_engineer.py | Line:148 | Generating Rolling Std features...
2026-09-03 15:14:09 | INFO | feature_engineer.py | Line:179 | Generating Lag Features...
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
2026-09-03 15:14:09 | INFO | feature_engineer.py | Line:205 | Generating Rate of Change features...
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (

Engineered: 154 columns

## 6- Feature Selection — Same Category Decision as the Main Pipeline

In [10]:
all_columns = [c for c in train_features.columns if c not in (ENGINE_COLUMN, TARGET_COLUMN, "regime")]
final_features = FeatureCategorySelector.exclude(all_columns, categories=["rolling"])
print(f"Selected {len(final_features)} features")

reducer = FeatureReducer(keep_features=final_features)
reducer.fit(train_features[all_columns])
reducer.save_selected_features(MODELS_DIR / "selected_features_regime_aware.json")

2026-09-03 15:14:16 | INFO | feature_selector.py | Line:114 | FeatureCategorySelector.exclude(['rolling']): dropped 42, kept 109 features.
2026-09-03 15:14:16 | INFO | feature_reducer.py | Line:101 | FeatureReducer: kept 109 features, removed 42.
2026-09-03 15:14:16 | INFO | feature_reducer.py | Line:154 | Selected feature list saved to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\selected_features_regime_aware.json

Selected 109 features

## 7- Final Scaling — Fit on Train Only

In [11]:
scaler = FeatureScaler()
X_train = scaler.fit_transform(train_features[final_features])
X_val = scaler.transform(val_features[final_features])
y_train = train_features[TARGET_COLUMN].reset_index(drop=True)
y_val = val_features[TARGET_COLUMN].reset_index(drop=True)

SCALERS_DIR.mkdir(parents=True, exist_ok=True)
scaler.save(SCALERS_DIR / "feature_scaler_regime_aware.pkl")
print(f"X_train: {X_train.shape}  X_val: {X_val.shape}")

2026-09-03 15:14:20 | INFO | feature_scaler.py | Line:33 | Fitting Feature Scaler...

2026-09-03 15:14:20 | INFO | feature_scaler.py | Line:37 | Feature Scaler fitted successfully.
2026-09-03 15:14:20 | INFO | feature_scaler.py | Line:44 | Transforming features...
2026-09-03 15:14:20 | INFO | feature_scaler.py | Line:60 | Feature transformation completed.
2026-09-03 15:14:20 | INFO | feature_scaler.py | Line:44 | Transforming features...
2026-09-03 15:14:20 | INFO | feature_scaler.py | Line:60 | Feature transformation completed.
2026-09-03 15:14:20 | INFO | feature_scaler.py | Line:89 | Scaler saved to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\scalers\feature_scaler_regime_aware.pkl

X_train: (49294, 109)  X_val: (11955, 109)

## 8- Tune Each Model Fresh

Re-tuned from scratch against the new regime-normalized features — the best
hyperparameters for the old globally-scaled features aren't guaranteed to be best here.

In [12]:
evaluator = RegressionEvaluator()
tuned_models = {}
val_results = []

for model_name in ["catboost", "xgboost", "lightgbm"]:

    print(f"--- Tuning {model_name} ---")
    tuner = ModelTuner(model_name, X_train, y_train, X_val, y_val, random_state=RANDOM_STATE)
    tuner.run(n_trials=N_TRIALS, show_progress_bar=True)

    best_params = tuner.best_params()
    print(f"{model_name} best params: {best_params}")

    final_model = ModelFactory.create(model_name, **best_params)
    final_trainer = BaseTrainer(
        final_model,
        run_name=f"{model_name}_regime_aware_final_tuned",
        tags={"model_family": model_name, "stage": "final_tuned_model", "normalization": "regime_aware"},
    )
    metrics = final_trainer.train(X_train, y_train, X_val, y_val)
    print(f"{model_name} final validation metrics: {metrics}\n")

    tuned_models[model_name] = final_model
    val_results.append({"Model": model_name, "Stage": "tuned_individual", **metrics})

    joblib.dump(final_model, MODELS_DIR / f"{model_name}_tuned_regime_aware.pkl")
    with open(MODELS_DIR / f"{model_name}_best_params_regime_aware.json", "w") as f:
        json.dump({"params": best_params, "metrics": metrics}, f, indent=2)

[I 2026-09-03 15:19:34,423] A new study created in memory with name: catboost_rul_optimization
2026-09-03 15:19:34 | INFO | hyperparameter_tuner.py | Line:142 | Starting Optuna search for catboost: 20 trials, search space = ['depth', 'learning_rate', 'iterations', 'l2_leaf_reg', 'subsample', 'random_strength']

--- Tuning catboost ---

  0%|          | 0/20 [00:00<?, ?it/s]2026-09-03 15:19:40 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...
2026-09-03 15:20:12 | INFO | base_trainer.py | Line:80 | Training completed successfully in 31.65s.
2026-09-03 15:20:12 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:20:12 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:20:12 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:20:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:20:26 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:20:26 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=9148ddbbe85f48b78d873b4382a3a4d1
2026-09-03 15:20:26 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 0 | MAE=17.7958 | RMSE=24.9674 | R2=0.7518 | Time=46.03s | params={'depth': 6, 'learning_rate': 0.2536999076681772, 'iterations': 1152, 'l2_leaf_reg': 6.387926357773329, 'subsample': 0.5780093202212182, 'random_strength': 1.5599452033620265}
Best trial: 0. Best value: 17.7958:   5%|▌         | 1/20 [00:52<16:28, 52.04s/it]2026-09-03 15:20:26 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:20:26,589] Trial 0 finished with value: 17.795813674483206 and parameters: {'depth': 6, 'learning_rate': 0.2536999076681772, 'iterations': 1152, 'l2_leaf_reg': 6.387926357773329, 'subsample': 0.5780093202212182, 'random_strength': 1.5599452033620265}. Best is trial 0 with value: 17.795813674483206.

2026-09-03 15:20:43 | INFO | base_trainer.py | Line:80 | Training completed successfully in 17.15s.
2026-09-03 15:20:43 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:20:43 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:20:43 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:20:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:20:48 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:20:48 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=b147eda7f4a843d686dc5229b60a16f0
2026-09-03 15:20:48 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 1 | MAE=17.3269 | RMSE=24.4070 | R2=0.7628 | Time=21.95s | params={'depth': 4, 'learning_rate': 0.19030368381735815, 'iterations': 982, 'l2_leaf_reg': 7.372653200164409, 'subsample': 0.5102922471479012, 'random_strength': 9.699098521619943}
Best trial: 1. Best value: 17.3269:  10%|█         | 2/20 [01:14<10:18, 34.35s/it]2026-09-03 15:20:48 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:20:48,555] Trial 1 finished with value: 17.32687778008188 and parameters: {'depth': 4, 'learning_rate': 0.19030368381735815, 'iterations': 982, 'l2_leaf_reg': 7.372653200164409, 'subsample': 0.5102922471479012, 'random_strength': 9.699098521619943}. Best is trial 1 with value: 17.32687778008188.

2026-09-03 15:21:39 | INFO | base_trainer.py | Line:80 | Training completed successfully in 50.63s.
2026-09-03 15:21:39 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:21:39 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:21:39 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:21:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:21:48 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:21:49 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=e86594587dc34f45a5f68db8ee6eb45d
2026-09-03 15:21:49 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 2 | MAE=17.5570 | RMSE=24.4692 | R2=0.7616 | Time=60.49s | params={'depth': 9, 'learning_rate': 0.020589728197687916, 'iterations': 436, 'l2_leaf_reg': 2.650640588680904, 'subsample': 0.6521211214797689, 'random_strength': 5.247564316322379}
Best trial: 1. Best value: 17.3269:  15%|█▌        | 3/20 [02:14<13:06, 46.29s/it]2026-09-03 15:21:49 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:21:49,052] Trial 2 finished with value: 17.556956011356117 and parameters: {'depth': 9, 'learning_rate': 0.020589728197687916, 'iterations': 436, 'l2_leaf_reg': 2.650640588680904, 'subsample': 0.6521211214797689, 'random_strength': 5.247564316322379}. Best is trial 1 with value: 17.32687778008188.

2026-09-03 15:22:28 | INFO | base_trainer.py | Line:80 | Training completed successfully in 39.38s.
2026-09-03 15:22:28 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:22:28 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:22:28 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:22:28 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:22:33 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:22:33 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=3120ffadd7c44b5c8e9bc570dd3cf914
2026-09-03 15:22:33 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 3 | MAE=17.0353 | RMSE=24.1757 | R2=0.7673 | Time=44.18s | params={'depth': 7, 'learning_rate': 0.02692655251486473, 'iterations': 996, 'l2_leaf_reg': 2.2554447458683766, 'subsample': 0.6460723242676091, 'random_strength': 3.663618432936917}
Best trial: 3. Best value: 17.0353:  20%|██        | 4/20 [02:58<12:07, 45.47s/it]2026-09-03 15:22:33 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:22:33,260] Trial 3 finished with value: 17.03534513462765 and parameters: {'depth': 7, 'learning_rate': 0.02692655251486473, 'iterations': 996, 'l2_leaf_reg': 2.2554447458683766, 'subsample': 0.6460723242676091, 'random_strength': 3.663618432936917}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:22:52 | INFO | base_trainer.py | Line:80 | Training completed successfully in 18.98s.
2026-09-03 15:22:52 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:22:52 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:22:52 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:22:52 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:22:57 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:22:57 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=d618d5ee72ce4665b8a74b78826c0bf5
2026-09-03 15:22:57 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 4 | MAE=17.1512 | RMSE=24.4103 | R2=0.7627 | Time=24.08s | params={'depth': 7, 'learning_rate': 0.14447746112718687, 'iterations': 459, 'l2_leaf_reg': 5.628109945722504, 'subsample': 0.7962072844310213, 'random_strength': 0.46450412719997725}
Best trial: 3. Best value: 17.0353:  25%|██▌       | 5/20 [03:22<09:26, 37.77s/it]2026-09-03 15:22:57 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:22:57,376] Trial 4 finished with value: 17.151222085730318 and parameters: {'depth': 7, 'learning_rate': 0.14447746112718687, 'iterations': 459, 'l2_leaf_reg': 5.628109945722504, 'subsample': 0.7962072844310213, 'random_strength': 0.46450412719997725}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:23:17 | INFO | base_trainer.py | Line:80 | Training completed successfully in 19.81s.
2026-09-03 15:23:17 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:23:17 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:23:17 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:23:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:23:22 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:23:22 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=c5504706c8844d689a74b37c7e252a74
2026-09-03 15:23:22 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 5 | MAE=18.2921 | RMSE=24.8754 | R2=0.7536 | Time=24.72s | params={'depth': 8, 'learning_rate': 0.0178601378893971, 'iterations': 284, 'l2_leaf_reg': 9.539969835279999, 'subsample': 0.9828160165372797, 'random_strength': 8.08397348116461}
Best trial: 3. Best value: 17.0353:  30%|███       | 6/20 [03:47<07:46, 33.34s/it]2026-09-03 15:23:22 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:23:22,109] Trial 5 finished with value: 18.292091288002556 and parameters: {'depth': 8, 'learning_rate': 0.0178601378893971, 'iterations': 284, 'l2_leaf_reg': 9.539969835279999, 'subsample': 0.9828160165372797, 'random_strength': 8.08397348116461}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:23:50 | INFO | base_trainer.py | Line:80 | Training completed successfully in 28.71s.
2026-09-03 15:23:50 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:23:50 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:23:50 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:23:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:23:55 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:23:55 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=01e8e5ef98d44ec486a3c31f981d10b3
2026-09-03 15:23:55 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 6 | MAE=17.3777 | RMSE=24.3364 | R2=0.7642 | Time=33.49s | params={'depth': 6, 'learning_rate': 0.013940346079873234, 'iterations': 1090, 'l2_leaf_reg': 4.961372443656412, 'subsample': 0.5610191174223894, 'random_strength': 4.951769101112702}
Best trial: 3. Best value: 17.0353:  35%|███▌      | 7/20 [04:21<07:14, 33.39s/it]2026-09-03 15:23:55 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:23:55,619] Trial 6 finished with value: 17.377657107925405 and parameters: {'depth': 6, 'learning_rate': 0.013940346079873234, 'iterations': 1090, 'l2_leaf_reg': 4.961372443656412, 'subsample': 0.5610191174223894, 'random_strength': 4.951769101112702}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:24:04 | INFO | base_trainer.py | Line:80 | Training completed successfully in 9.05s.
2026-09-03 15:24:04 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:24:04 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:24:04 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:24:04 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:24:10 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:24:10 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=37f35f5ab54b4558809243679736a462
2026-09-03 15:24:10 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 7 | MAE=17.3843 | RMSE=24.5127 | R2=0.7607 | Time=14.49s | params={'depth': 4, 'learning_rate': 0.22038218939289875, 'iterations': 536, 'l2_leaf_reg': 6.962700559185838, 'subsample': 0.6558555380447055, 'random_strength': 5.200680211778108}
Best trial: 3. Best value: 17.0353:  40%|████      | 8/20 [04:35<05:28, 27.38s/it]2026-09-03 15:24:10 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:24:10,126] Trial 7 finished with value: 17.384301544694793 and parameters: {'depth': 4, 'learning_rate': 0.22038218939289875, 'iterations': 536, 'l2_leaf_reg': 6.962700559185838, 'subsample': 0.6558555380447055, 'random_strength': 5.200680211778108}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:25:11 | INFO | base_trainer.py | Line:80 | Training completed successfully in 61.77s.
2026-09-03 15:25:11 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:25:11 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:25:11 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:25:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:25:16 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:25:16 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=032fa339d8b346c1aacd824f2e29a03a
2026-09-03 15:25:16 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 8 | MAE=17.0751 | RMSE=24.1689 | R2=0.7674 | Time=66.29s | params={'depth': 7, 'learning_rate': 0.01875220945578641, 'iterations': 1461, 'l2_leaf_reg': 7.976195410250031, 'subsample': 0.9697494707820946, 'random_strength': 8.948273504276488}
Best trial: 3. Best value: 17.0353:  45%|████▌     | 9/20 [05:41<07:15, 39.55s/it]2026-09-03 15:25:16 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:25:16,445] Trial 8 finished with value: 17.075127441009993 and parameters: {'depth': 7, 'learning_rate': 0.01875220945578641, 'iterations': 1461, 'l2_leaf_reg': 7.976195410250031, 'subsample': 0.9697494707820946, 'random_strength': 8.948273504276488}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:25:39 | INFO | base_trainer.py | Line:80 | Training completed successfully in 23.28s.
2026-09-03 15:25:39 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:25:39 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:25:39 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:25:39 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:25:48 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:25:48 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=aac21c3eda2d465ea00a0f5d4c9d18b7
2026-09-03 15:25:48 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 9 | MAE=17.5141 | RMSE=24.6842 | R2=0.7574 | Time=32.42s | params={'depth': 8, 'learning_rate': 0.22999586428143728, 'iterations': 315, 'l2_leaf_reg': 2.763845761772307, 'subsample': 0.522613644455269, 'random_strength': 3.2533033076326436}
Best trial: 3. Best value: 17.0353:  50%|█████     | 10/20 [06:14<06:13, 37.36s/it]2026-09-03 15:25:48 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:25:48,888] Trial 9 finished with value: 17.514072860095386 and parameters: {'depth': 8, 'learning_rate': 0.22999586428143728, 'iterations': 315, 'l2_leaf_reg': 2.763845761772307, 'subsample': 0.522613644455269, 'random_strength': 3.2533033076326436}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:30:28 | INFO | base_trainer.py | Line:80 | Training completed successfully in 279.67s.
2026-09-03 15:30:28 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:30:28 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:30:28 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:30:28 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:30:35 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:30:35 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=c59893fb75ab4c5ba469d5c0b8a314b5
2026-09-03 15:30:35 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 10 | MAE=17.1299 | RMSE=24.3952 | R2=0.7630 | Time=286.13s | params={'depth': 10, 'learning_rate': 0.050022091577274753, 'iterations': 759, 'l2_leaf_reg': 1.1616568805333802, 'subsample': 0.8259332753890892, 'random_strength': 7.331983444045203}
Best trial: 3. Best value: 17.0353:  55%|█████▌    | 11/20 [11:00<17:01, 113.52s/it]2026-09-03 15:30:35 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:30:35,096] Trial 10 finished with value: 17.129861171599984 and parameters: {'depth': 10, 'learning_rate': 0.050022091577274753, 'iterations': 759, 'l2_leaf_reg': 1.1616568805333802, 'subsample': 0.8259332753890892, 'random_strength': 7.331983444045203}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:31:17 | INFO | base_trainer.py | Line:80 | Training completed successfully in 42.70s.
2026-09-03 15:31:17 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:31:17 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:31:17 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:31:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:31:22 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:31:22 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=941f0749bf4d4664b2d78170ad13692d
2026-09-03 15:31:22 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 11 | MAE=17.0484 | RMSE=24.1963 | R2=0.7669 | Time=47.17s | params={'depth': 6, 'learning_rate': 0.03799273062329156, 'iterations': 1431, 'l2_leaf_reg': 9.943509196092139, 'subsample': 0.9951933882660442, 'random_strength': 9.458097199737129}
Best trial: 3. Best value: 17.0353:  60%|██████    | 12/20 [11:47<12:26, 93.34s/it] 2026-09-03 15:31:22 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:31:22,295] Trial 11 finished with value: 17.048416775146464 and parameters: {'depth': 6, 'learning_rate': 0.03799273062329156, 'iterations': 1431, 'l2_leaf_reg': 9.943509196092139, 'subsample': 0.9951933882660442, 'random_strength': 9.458097199737129}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:31:51 | INFO | base_trainer.py | Line:80 | Training completed successfully in 29.28s.
2026-09-03 15:31:51 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:31:51 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:31:51 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:31:51 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:31:56 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:31:56 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=5481a39e0c764ada9402f6467b8cdae8
2026-09-03 15:31:56 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 12 | MAE=17.0731 | RMSE=24.2096 | R2=0.7666 | Time=33.97s | params={'depth': 5, 'learning_rate': 0.043812383564303524, 'iterations': 1483, 'l2_leaf_reg': 9.420056884732823, 'subsample': 0.8486943041334339, 'random_strength': 6.841538156950666}
Best trial: 3. Best value: 17.0353:  65%|██████▌   | 13/20 [12:21<08:47, 75.37s/it]2026-09-03 15:31:56 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:31:56,302] Trial 12 finished with value: 17.073145156994407 and parameters: {'depth': 5, 'learning_rate': 0.043812383564303524, 'iterations': 1483, 'l2_leaf_reg': 9.420056884732823, 'subsample': 0.8486943041334339, 'random_strength': 6.841538156950666}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:32:31 | INFO | base_trainer.py | Line:80 | Training completed successfully in 35.15s.
2026-09-03 15:32:31 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:32:31 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:32:31 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:32:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:32:37 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:32:37 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=38944129aff3400ab5329fd8531342ce
2026-09-03 15:32:37 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 13 | MAE=17.0697 | RMSE=24.2662 | R2=0.7655 | Time=41.42s | params={'depth': 6, 'learning_rate': 0.037370046395123875, 'iterations': 1289, 'l2_leaf_reg': 4.1112437072344, 'subsample': 0.7345943907354787, 'random_strength': 2.7448497328248096}
Best trial: 3. Best value: 17.0353:  70%|███████   | 14/20 [13:03<06:30, 65.13s/it]2026-09-03 15:32:37 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:32:37,756] Trial 13 finished with value: 17.06967156764981 and parameters: {'depth': 6, 'learning_rate': 0.037370046395123875, 'iterations': 1289, 'l2_leaf_reg': 4.1112437072344, 'subsample': 0.7345943907354787, 'random_strength': 2.7448497328248096}. Best is trial 3 with value: 17.03534513462765.

2026-09-03 15:33:16 | INFO | base_trainer.py | Line:80 | Training completed successfully in 38.27s.
2026-09-03 15:33:16 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:33:16 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:33:16 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:33:16 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:33:23 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:33:23 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=4674144f110d4f56a0da73e6fca1b4b4
2026-09-03 15:33:23 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 14 | MAE=17.0138 | RMSE=24.1805 | R2=0.7672 | Time=45.63s | params={'depth': 7, 'learning_rate': 0.07396712122188455, 'iterations': 826, 'l2_leaf_reg': 8.43859881923083, 'subsample': 0.9145507642489262, 'random_strength': 3.4376131257215317}
Best trial: 14. Best value: 17.0138:  75%|███████▌  | 15/20 [13:48<04:56, 59.27s/it]2026-09-03 15:33:23 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:33:23,436] Trial 14 finished with value: 17.013810479720423 and parameters: {'depth': 7, 'learning_rate': 0.07396712122188455, 'iterations': 826, 'l2_leaf_reg': 8.43859881923083, 'subsample': 0.9145507642489262, 'random_strength': 3.4376131257215317}. Best is trial 14 with value: 17.013810479720423.

2026-09-03 15:34:20 | INFO | base_trainer.py | Line:80 | Training completed successfully in 57.12s.
2026-09-03 15:34:20 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:34:20 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:34:20 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:34:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:34:26 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:34:26 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=812e3e83d9284b3b87184a954ccb82a2
2026-09-03 15:34:26 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 15 | MAE=17.2427 | RMSE=24.4582 | R2=0.7618 | Time=62.67s | params={'depth': 8, 'learning_rate': 0.08817206035993924, 'iterations': 792, 'l2_leaf_reg': 1.4493030799966187, 'subsample': 0.8989974345395084, 'random_strength': 3.3436014458720065}
Best trial: 14. Best value: 17.0138:  80%|████████  | 16/20 [14:51<04:01, 60.30s/it]2026-09-03 15:34:26 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:34:26,145] Trial 15 finished with value: 17.24268276511474 and parameters: {'depth': 8, 'learning_rate': 0.08817206035993924, 'iterations': 792, 'l2_leaf_reg': 1.4493030799966187, 'subsample': 0.8989974345395084, 'random_strength': 3.3436014458720065}. Best is trial 14 with value: 17.013810479720423.

2026-09-03 15:34:58 | INFO | base_trainer.py | Line:80 | Training completed successfully in 31.88s.
2026-09-03 15:34:58 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:34:58 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:34:58 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:34:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:35:02 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:35:02 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=9216b6dd651c4294bf4fe3ccff1b2251
2026-09-03 15:35:02 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 16 | MAE=17.1818 | RMSE=24.3548 | R2=0.7638 | Time=36.63s | params={'depth': 7, 'learning_rate': 0.09903486282791328, 'iterations': 801, 'l2_leaf_reg': 8.357655265658407, 'subsample': 0.7212958229341726, 'random_strength': 4.337368778796865}
Best trial: 14. Best value: 17.0138:  85%|████████▌ | 17/20 [15:28<02:39, 53.19s/it]2026-09-03 15:35:02 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:35:02,817] Trial 16 finished with value: 17.181794562111232 and parameters: {'depth': 7, 'learning_rate': 0.09903486282791328, 'iterations': 801, 'l2_leaf_reg': 8.357655265658407, 'subsample': 0.7212958229341726, 'random_strength': 4.337368778796865}. Best is trial 14 with value: 17.013810479720423.

2026-09-03 15:36:25 | INFO | base_trainer.py | Line:80 | Training completed successfully in 82.61s.
2026-09-03 15:36:25 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:36:25 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:36:25 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:36:25 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:36:30 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:36:30 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=6c20f35f87bb48e8a08c80904f4612c3
2026-09-03 15:36:30 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 17 | MAE=17.1166 | RMSE=24.3321 | R2=0.7642 | Time=88.09s | params={'depth': 9, 'learning_rate': 0.06798195166743463, 'iterations': 685, 'l2_leaf_reg': 4.086756929635756, 'subsample': 0.913354883025834, 'random_strength': 1.8540267593127382}
Best trial: 14. Best value: 17.0138:  90%|█████████ | 18/20 [16:56<02:07, 63.70s/it]2026-09-03 15:36:30 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:36:30,955] Trial 17 finished with value: 17.116581095694155 and parameters: {'depth': 9, 'learning_rate': 0.06798195166743463, 'iterations': 685, 'l2_leaf_reg': 4.086756929635756, 'subsample': 0.913354883025834, 'random_strength': 1.8540267593127382}. Best is trial 14 with value: 17.013810479720423.

2026-09-03 15:36:57 | INFO | base_trainer.py | Line:80 | Training completed successfully in 26.01s.
2026-09-03 15:36:57 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:36:57 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:36:57 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:36:57 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:37:01 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:37:02 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=69489f4d4fc741548916497ac236ec47
2026-09-03 15:37:02 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 18 | MAE=17.1577 | RMSE=24.2422 | R2=0.7660 | Time=31.03s | params={'depth': 5, 'learning_rate': 0.02835061756144842, 'iterations': 929, 'l2_leaf_reg': 2.660926653756605, 'subsample': 0.7446710338810353, 'random_strength': 6.200616669627836}
Best trial: 14. Best value: 17.0138:  95%|█████████▌| 19/20 [17:27<00:53, 53.89s/it]2026-09-03 15:37:02 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:37:02,024] Trial 18 finished with value: 17.15766245074701 and parameters: {'depth': 5, 'learning_rate': 0.02835061756144842, 'iterations': 929, 'l2_leaf_reg': 2.660926653756605, 'subsample': 0.7446710338810353, 'random_strength': 6.200616669627836}. Best is trial 14 with value: 17.013810479720423.

2026-09-03 15:40:02 | INFO | base_trainer.py | Line:80 | Training completed successfully in 180.36s.
2026-09-03 15:40:02 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:40:02 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:40:02 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:40:02 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:40:23 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:40:23 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=c5eb3eb23b4d4fd5ae0cfc8dfe109b2e
2026-09-03 15:40:23 | INFO | hyperparameter_tuner.py | Line:219 | [catboost] Trial 19 | MAE=17.4439 | RMSE=24.3917 | R2=0.7631 | Time=201.52s | params={'depth': 9, 'learning_rate': 0.010498780740356898, 'iterations': 954, 'l2_leaf_reg': 5.846204916847864, 'subsample': 0.6639926607342311, 'random_strength': 4.165147433416073}
Best trial: 14. Best value: 17.0138: 100%|██████████| 20/20 [20:49<00:00, 62.45s/it]
2026-09-03 15:40:23 | INFO | hyperparameter_tuner.py | Line:154 | [catboost] Optimization finished. Best MAE = 17.0138 at trial 14.
2026-09-03 15:40:23 | INFO | base_trainer.py | Line:74 | Training CatBoostRegressor...

[I 2026-09-03 15:40:23,610] Trial 19 finished with value: 17.443897126936292 and parameters: {'depth': 9, 'learning_rate': 0.010498780740356898, 'iterations': 954, 'l2_leaf_reg': 5.846204916847864, 'subsample': 0.6639926607342311, 'random_strength': 4.165147433416073}. Best is trial 14 with value: 17.013810479720423.
catboost best params: {'random_state': 42, 'verbose': False, 'depth': 7, 'learning_rate': 0.07396712122188455, 'iterations': 826, 'l2_leaf_reg': 8.43859881923083, 'subsample': 0.9145507642489262, 'random_strength': 3.4376131257215317}

2026-09-03 15:42:04 | INFO | base_trainer.py | Line:80 | Training completed successfully in 101.04s.
2026-09-03 15:42:04 | INFO | base_trainer.py | Line:129 | Generating predictions using CatBoostRegressor...
2026-09-03 15:42:04 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:42:04 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:42:05 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:42:32 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:42:32 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=bad7e7463ce1482b9f20518a87fd542f
[I 2026-09-03 15:42:32,914] A new study created in memory with name: xgboost_rul_optimization
2026-09-03 15:42:32 | INFO | hyperparameter_tuner.py | Line:142 | Starting Optuna search for xgboost: 20 trials, search space = ['max_depth', 'learning_rate', 'n_estimators', 'reg_lambda', 'subsample', 'colsample_bytree']

catboost final validation metrics: {'MAE': 17.013810479720423, 'RMSE': 24.180505708286077, 'R2': 0.7671660767746313, 'MAPE': 25.31010039384351, 'Training Time (s)': 101.04}

--- Tuning xgboost ---

  0%|          | 0/20 [00:00<?, ?it/s]2026-09-03 15:42:32 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...
2026-09-03 15:43:40 | INFO | base_trainer.py | Line:80 | Training completed successfully in 67.96s.
2026-09-03 15:43:40 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:43:41 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:43:41 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:43:41 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:44:00 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:44:00 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=3e5444c03ac0443fa64cb3b787890807
2026-09-03 15:44:00 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 0 | MAE=18.9923 | RMSE=26.2460 | R2=0.7257 | Time=87.84s | params={'max_depth': 5, 'learning_rate': 0.2536999076681772, 'n_estimators': 1152, 'reg_lambda': 6.387926357773329, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014}
Best trial: 0. Best value: 18.9923:   5%|▌         | 1/20 [01:27<27:50, 87.90s/it]2026-09-03 15:44:00 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:44:00,824] Trial 0 finished with value: 18.992250442504883 and parameters: {'max_depth': 5, 'learning_rate': 0.2536999076681772, 'n_estimators': 1152, 'reg_lambda': 6.387926357773329, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.5779972601681014}. Best is trial 0 with value: 18.992250442504883.

2026-09-03 15:44:26 | INFO | base_trainer.py | Line:80 | Training completed successfully in 26.11s.
2026-09-03 15:44:26 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:44:27 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:44:27 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:44:27 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:44:51 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:44:51 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=7fcf7bf8157342608eeec7d73acf968e
2026-09-03 15:44:51 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 1 | MAE=17.8564 | RMSE=24.9404 | R2=0.7523 | Time=50.53s | params={'max_depth': 3, 'learning_rate': 0.19030368381735815, 'n_estimators': 982, 'reg_lambda': 7.372653200164409, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971}
Best trial: 1. Best value: 17.8564:  10%|█         | 2/20 [02:18<19:47, 65.94s/it]2026-09-03 15:44:51 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:44:51,391] Trial 1 finished with value: 17.856435775756836 and parameters: {'max_depth': 3, 'learning_rate': 0.19030368381735815, 'n_estimators': 982, 'reg_lambda': 7.372653200164409, 'subsample': 0.5102922471479012, 'colsample_bytree': 0.9849549260809971}. Best is trial 1 with value: 17.856435775756836.

2026-09-03 15:46:17 | INFO | base_trainer.py | Line:80 | Training completed successfully in 86.49s.
2026-09-03 15:46:17 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:46:18 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:46:18 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:46:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:46:41 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:46:42 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=8b8cffc28cc6494b9739ec81f80bb0bd
2026-09-03 15:46:42 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 2 | MAE=16.9189 | RMSE=24.3218 | R2=0.7644 | Time=110.62s | params={'max_depth': 9, 'learning_rate': 0.020589728197687916, 'n_estimators': 436, 'reg_lambda': 2.650640588680904, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119}
Best trial: 2. Best value: 16.9189:  15%|█▌        | 3/20 [04:09<24:28, 86.38s/it]2026-09-03 15:46:42 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:46:42,088] Trial 2 finished with value: 16.918922424316406 and parameters: {'max_depth': 9, 'learning_rate': 0.020589728197687916, 'n_estimators': 436, 'reg_lambda': 2.650640588680904, 'subsample': 0.6521211214797689, 'colsample_bytree': 0.762378215816119}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 15:47:42 | INFO | base_trainer.py | Line:80 | Training completed successfully in 60.59s.
2026-09-03 15:47:42 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:47:43 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:47:43 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:47:43 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:47:59 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:47:59 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=424974ee29af44348f217262770a6383
2026-09-03 15:47:59 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 3 | MAE=17.1004 | RMSE=24.4402 | R2=0.7621 | Time=77.84s | params={'max_depth': 6, 'learning_rate': 0.02692655251486473, 'n_estimators': 996, 'reg_lambda': 2.2554447458683766, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459}
Best trial: 2. Best value: 16.9189:  20%|██        | 4/20 [05:27<22:08, 83.03s/it]2026-09-03 15:48:00 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:47:59,987] Trial 3 finished with value: 17.100378036499023 and parameters: {'max_depth': 6, 'learning_rate': 0.02692655251486473, 'n_estimators': 996, 'reg_lambda': 2.2554447458683766, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.6831809216468459}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 15:48:17 | INFO | base_trainer.py | Line:80 | Training completed successfully in 17.87s.
2026-09-03 15:48:17 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:48:18 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:48:18 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:48:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:48:26 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:48:26 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=9cbffad1f45b43d0b3246519dfa80f18
2026-09-03 15:48:26 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 4 | MAE=17.5780 | RMSE=24.9506 | R2=0.7521 | Time=26.19s | params={'max_depth': 6, 'learning_rate': 0.14447746112718687, 'n_estimators': 459, 'reg_lambda': 5.628109945722504, 'subsample': 0.7962072844310213, 'colsample_bytree': 0.5232252063599989}
Best trial: 2. Best value: 16.9189:  25%|██▌       | 5/20 [05:53<15:38, 62.55s/it]2026-09-03 15:48:26 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:48:26,230] Trial 4 finished with value: 17.57802391052246 and parameters: {'max_depth': 6, 'learning_rate': 0.14447746112718687, 'n_estimators': 459, 'reg_lambda': 5.628109945722504, 'subsample': 0.7962072844310213, 'colsample_bytree': 0.5232252063599989}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 15:48:56 | INFO | base_trainer.py | Line:80 | Training completed successfully in 29.80s.
2026-09-03 15:48:56 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:48:56 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:48:56 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:48:56 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:49:19 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:49:20 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=03e1a864dab14bd09109e75ea67a1d61
2026-09-03 15:49:20 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 5 | MAE=17.1338 | RMSE=24.3553 | R2=0.7638 | Time=53.87s | params={'max_depth': 7, 'learning_rate': 0.0178601378893971, 'n_estimators': 284, 'reg_lambda': 9.539969835279999, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306}
Best trial: 2. Best value: 16.9189:  30%|███       | 6/20 [06:47<13:54, 59.61s/it]2026-09-03 15:49:20 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:49:20,136] Trial 5 finished with value: 17.133821487426758 and parameters: {'max_depth': 7, 'learning_rate': 0.0178601378893971, 'n_estimators': 284, 'reg_lambda': 9.539969835279999, 'subsample': 0.9828160165372797, 'colsample_bytree': 0.9041986740582306}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 15:50:07 | INFO | base_trainer.py | Line:80 | Training completed successfully in 47.48s.
2026-09-03 15:50:07 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:50:07 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:50:07 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:50:08 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:50:22 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:50:22 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=1a674aab2c7c4349879ad6780bc76f1d
2026-09-03 15:50:22 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 6 | MAE=17.1440 | RMSE=24.3704 | R2=0.7635 | Time=62.36s | params={'max_depth': 5, 'learning_rate': 0.013940346079873234, 'n_estimators': 1090, 'reg_lambda': 4.961372443656412, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351}
Best trial: 2. Best value: 16.9189:  35%|███▌      | 7/20 [07:49<13:06, 60.52s/it]2026-09-03 15:50:22 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:50:22,542] Trial 6 finished with value: 17.143951416015625 and parameters: {'max_depth': 5, 'learning_rate': 0.013940346079873234, 'n_estimators': 1090, 'reg_lambda': 4.961372443656412, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 15:50:35 | INFO | base_trainer.py | Line:80 | Training completed successfully in 12.46s.
2026-09-03 15:50:35 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:50:35 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:50:35 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:50:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:50:57 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:50:57 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=67155dff0b7c4408ad6405643da90746
2026-09-03 15:50:57 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 7 | MAE=17.8121 | RMSE=24.8807 | R2=0.7535 | Time=34.74s | params={'max_depth': 3, 'learning_rate': 0.22038218939289875, 'n_estimators': 536, 'reg_lambda': 6.962700559185838, 'subsample': 0.6558555380447055, 'colsample_bytree': 0.7600340105889054}
Best trial: 2. Best value: 16.9189:  40%|████      | 8/20 [08:24<10:27, 52.33s/it]2026-09-03 15:50:57 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:50:57,297] Trial 7 finished with value: 17.81208610534668 and parameters: {'max_depth': 3, 'learning_rate': 0.22038218939289875, 'n_estimators': 536, 'reg_lambda': 6.962700559185838, 'subsample': 0.6558555380447055, 'colsample_bytree': 0.7600340105889054}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 15:53:20 | INFO | base_trainer.py | Line:80 | Training completed successfully in 142.94s.
2026-09-03 15:53:20 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:53:20 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:53:20 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:53:21 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:53:48 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:53:48 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=81ee2474447948c0a4791136dfbb1dd7
2026-09-03 15:53:48 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 8 | MAE=17.0370 | RMSE=24.4880 | R2=0.7612 | Time=170.87s | params={'max_depth': 7, 'learning_rate': 0.01875220945578641, 'n_estimators': 1461, 'reg_lambda': 7.976195410250031, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245}
Best trial: 2. Best value: 16.9189:  45%|████▌     | 9/20 [11:15<16:23, 89.41s/it]2026-09-03 15:53:48 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:53:48,259] Trial 8 finished with value: 17.037031173706055 and parameters: {'max_depth': 7, 'learning_rate': 0.01875220945578641, 'n_estimators': 1461, 'reg_lambda': 7.976195410250031, 'subsample': 0.9697494707820946, 'colsample_bytree': 0.9474136752138245}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 15:54:11 | INFO | base_trainer.py | Line:80 | Training completed successfully in 23.64s.
2026-09-03 15:54:11 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:54:12 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:54:12 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:54:12 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:54:19 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:54:19 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=633c83e4b8504c1288dec46d91122342
2026-09-03 15:54:19 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 9 | MAE=18.4958 | RMSE=25.8862 | R2=0.7332 | Time=30.85s | params={'max_depth': 7, 'learning_rate': 0.22999586428143728, 'n_estimators': 315, 'reg_lambda': 2.763845761772307, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322}
Best trial: 2. Best value: 16.9189:  50%|█████     | 10/20 [11:46<11:53, 71.34s/it]2026-09-03 15:54:19 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:54:19,163] Trial 9 finished with value: 18.495845794677734 and parameters: {'max_depth': 7, 'learning_rate': 0.22999586428143728, 'n_estimators': 315, 'reg_lambda': 2.763845761772307, 'subsample': 0.522613644455269, 'colsample_bytree': 0.6626651653816322}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 15:56:47 | INFO | base_trainer.py | Line:80 | Training completed successfully in 148.67s.
2026-09-03 15:56:47 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 15:56:48 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 15:56:48 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 15:56:48 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 15:57:01 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 15:57:02 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=43371cebab174a8f859033bdf04ac621
2026-09-03 15:57:02 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 10 | MAE=17.0773 | RMSE=24.5407 | R2=0.7602 | Time=162.88s | params={'max_depth': 10, 'learning_rate': 0.050022091577274753, 'n_estimators': 682, 'reg_lambda': 1.1616568805333802, 'subsample': 0.8259332753890892, 'colsample_bytree': 0.8451235367845726}
Best trial: 2. Best value: 16.9189:  55%|█████▌    | 11/20 [14:29<14:54, 99.38s/it]2026-09-03 15:57:02 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 15:57:02,109] Trial 10 finished with value: 17.077289581298828 and parameters: {'max_depth': 10, 'learning_rate': 0.050022091577274753, 'n_estimators': 682, 'reg_lambda': 1.1616568805333802, 'subsample': 0.8259332753890892, 'colsample_bytree': 0.8451235367845726}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 16:02:13 | INFO | base_trainer.py | Line:80 | Training completed successfully in 311.39s.
2026-09-03 16:02:13 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 16:02:13 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:02:13 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:02:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:02:23 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:02:23 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=86e69b213564455fa3cb482c0688607c
2026-09-03 16:02:23 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 11 | MAE=17.0264 | RMSE=24.5420 | R2=0.7602 | Time=320.97s | params={'max_depth': 10, 'learning_rate': 0.03799273062329156, 'n_estimators': 1431, 'reg_lambda': 9.944293907519794, 'subsample': 0.9952369868388061, 'colsample_bytree': 0.9729048599868564}
Best trial: 2. Best value: 16.9189:  60%|██████    | 12/20 [19:50<22:14, 166.84s/it]2026-09-03 16:02:23 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 16:02:23,255] Trial 11 finished with value: 17.026397705078125 and parameters: {'max_depth': 10, 'learning_rate': 0.03799273062329156, 'n_estimators': 1431, 'reg_lambda': 9.944293907519794, 'subsample': 0.9952369868388061, 'colsample_bytree': 0.9729048599868564}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 16:08:13 | INFO | base_trainer.py | Line:80 | Training completed successfully in 350.45s.
2026-09-03 16:08:13 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 16:08:14 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:08:14 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:08:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:08:20 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:08:20 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=66bece5eb245473cb8ccd018d2e24775
2026-09-03 16:08:20 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 12 | MAE=17.1030 | RMSE=24.5805 | R2=0.7594 | Time=356.97s | params={'max_depth': 10, 'learning_rate': 0.0462509327072741, 'n_estimators': 1481, 'reg_lambda': 4.05963949553049, 'subsample': 0.84996165815996, 'colsample_bytree': 0.8520450009786442}
Best trial: 2. Best value: 16.9189:  65%|██████▌   | 13/20 [25:47<26:11, 224.47s/it]2026-09-03 16:08:20 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 16:08:20,333] Trial 12 finished with value: 17.102954864501953 and parameters: {'max_depth': 10, 'learning_rate': 0.0462509327072741, 'n_estimators': 1481, 'reg_lambda': 4.05963949553049, 'subsample': 0.84996165815996, 'colsample_bytree': 0.8520450009786442}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 16:09:35 | INFO | base_trainer.py | Line:80 | Training completed successfully in 74.68s.
2026-09-03 16:09:35 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 16:09:35 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:09:35 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:09:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:09:40 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:09:40 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=3ea42e126efe4895b94c5c98ba5144f1
2026-09-03 16:09:40 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 13 | MAE=17.0646 | RMSE=24.4873 | R2=0.7612 | Time=80.15s | params={'max_depth': 9, 'learning_rate': 0.04078488503903071, 'n_estimators': 789, 'reg_lambda': 9.972898084764783, 'subsample': 0.7364899611617342, 'colsample_bytree': 0.8263406001124904}
Best trial: 2. Best value: 16.9189:  70%|███████   | 14/20 [27:07<18:05, 180.89s/it]2026-09-03 16:09:40 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 16:09:40,524] Trial 13 finished with value: 17.06458282470703 and parameters: {'max_depth': 9, 'learning_rate': 0.04078488503903071, 'n_estimators': 789, 'reg_lambda': 9.972898084764783, 'subsample': 0.7364899611617342, 'colsample_bytree': 0.8263406001124904}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 16:11:30 | INFO | base_trainer.py | Line:80 | Training completed successfully in 110.26s.
2026-09-03 16:11:30 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 16:11:31 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:11:31 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:11:31 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:11:36 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:11:36 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=561835f82b744b1caad5c483b6637fe5
2026-09-03 16:11:36 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 14 | MAE=17.1184 | RMSE=24.5559 | R2=0.7599 | Time=115.74s | params={'max_depth': 9, 'learning_rate': 0.07293223654954831, 'n_estimators': 1231, 'reg_lambda': 8.479162120156472, 'subsample': 0.915296768828018, 'colsample_bytree': 0.7591784144998813}
Best trial: 2. Best value: 16.9189:  75%|███████▌  | 15/20 [29:03<13:26, 161.27s/it]2026-09-03 16:11:36 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 16:11:36,311] Trial 14 finished with value: 17.118432998657227 and parameters: {'max_depth': 9, 'learning_rate': 0.07293223654954831, 'n_estimators': 1231, 'reg_lambda': 8.479162120156472, 'subsample': 0.915296768828018, 'colsample_bytree': 0.7591784144998813}. Best is trial 2 with value: 16.918922424316406.

2026-09-03 16:12:58 | INFO | base_trainer.py | Line:80 | Training completed successfully in 82.27s.
2026-09-03 16:12:58 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 16:12:58 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:12:58 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:12:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:13:03 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:13:03 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=81730bf4b20847a4896db2399faa4e2d
2026-09-03 16:13:03 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 15 | MAE=16.9081 | RMSE=24.3726 | R2=0.7635 | Time=87.65s | params={'max_depth': 9, 'learning_rate': 0.0105058180103052, 'n_estimators': 827, 'reg_lambda': 3.975217011867933, 'subsample': 0.7344445913937097, 'colsample_bytree': 0.9990531660228786}
Best trial: 15. Best value: 16.9081:  80%|████████  | 16/20 [30:31<09:16, 139.12s/it]2026-09-03 16:13:04 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 16:13:03,995] Trial 15 finished with value: 16.908100128173828 and parameters: {'max_depth': 9, 'learning_rate': 0.0105058180103052, 'n_estimators': 827, 'reg_lambda': 3.975217011867933, 'subsample': 0.7344445913937097, 'colsample_bytree': 0.9990531660228786}. Best is trial 15 with value: 16.908100128173828.

2026-09-03 16:13:46 | INFO | base_trainer.py | Line:80 | Training completed successfully in 42.71s.
2026-09-03 16:13:46 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 16:13:46 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:13:46 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:13:46 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:13:51 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:13:51 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=ce584a9218324119a51406eaeb1e658a
2026-09-03 16:13:51 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 16 | MAE=16.9064 | RMSE=24.2275 | R2=0.7663 | Time=47.88s | params={'max_depth': 8, 'learning_rate': 0.01023651005379198, 'n_estimators': 763, 'reg_lambda': 3.6736039846577295, 'subsample': 0.712949409808687, 'colsample_bytree': 0.6286191428179753}
Best trial: 16. Best value: 16.9064:  85%|████████▌ | 17/20 [31:18<05:35, 111.69s/it]2026-09-03 16:13:51 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 16:13:51,917] Trial 16 finished with value: 16.906381607055664 and parameters: {'max_depth': 8, 'learning_rate': 0.01023651005379198, 'n_estimators': 763, 'reg_lambda': 3.6736039846577295, 'subsample': 0.712949409808687, 'colsample_bytree': 0.6286191428179753}. Best is trial 16 with value: 16.906381607055664.

2026-09-03 16:14:35 | INFO | base_trainer.py | Line:80 | Training completed successfully in 43.85s.
2026-09-03 16:14:35 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 16:14:35 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:14:35 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:14:36 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:14:40 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:14:40 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=f433dc23516c41e8b24daaa2fbbd57b8
2026-09-03 16:14:40 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 17 | MAE=16.9094 | RMSE=24.2676 | R2=0.7655 | Time=48.93s | params={'max_depth': 8, 'learning_rate': 0.01170228053203875, 'n_estimators': 788, 'reg_lambda': 4.025164201555733, 'subsample': 0.7245485353089308, 'colsample_bytree': 0.6153852668949172}
Best trial: 16. Best value: 16.9064:  90%|█████████ | 18/20 [32:07<03:05, 92.84s/it] 2026-09-03 16:14:40 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 16:14:40,871] Trial 17 finished with value: 16.909404754638672 and parameters: {'max_depth': 8, 'learning_rate': 0.01170228053203875, 'n_estimators': 788, 'reg_lambda': 4.025164201555733, 'subsample': 0.7245485353089308, 'colsample_bytree': 0.6153852668949172}. Best is trial 16 with value: 16.906381607055664.

2026-09-03 16:15:18 | INFO | base_trainer.py | Line:80 | Training completed successfully in 37.61s.
2026-09-03 16:15:18 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 16:15:18 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:15:18 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:15:18 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:15:23 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:15:23 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=71ff53e799924af2b9a22775414010b4
2026-09-03 16:15:23 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 18 | MAE=16.9145 | RMSE=24.1949 | R2=0.7669 | Time=42.94s | params={'max_depth': 8, 'learning_rate': 0.010281029380118533, 'n_estimators': 671, 'reg_lambda': 3.915716514051399, 'subsample': 0.7780087404263399, 'colsample_bytree': 0.5566158446938569}
Best trial: 16. Best value: 16.9064:  95%|█████████▌| 19/20 [32:50<01:17, 77.86s/it]2026-09-03 16:15:23 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 16:15:23,829] Trial 18 finished with value: 16.9145450592041 and parameters: {'max_depth': 8, 'learning_rate': 0.010281029380118533, 'n_estimators': 671, 'reg_lambda': 3.915716514051399, 'subsample': 0.7780087404263399, 'colsample_bytree': 0.5566158446938569}. Best is trial 16 with value: 16.906381607055664.

2026-09-03 16:16:11 | INFO | base_trainer.py | Line:80 | Training completed successfully in 47.77s.
2026-09-03 16:16:11 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 16:16:11 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:16:11 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:16:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:16:16 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:16:16 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=931a95128f434c298ef8442ac6cbb215
2026-09-03 16:16:16 | INFO | hyperparameter_tuner.py | Line:219 | [xgboost] Trial 19 | MAE=16.9126 | RMSE=24.2654 | R2=0.7655 | Time=53.06s | params={'max_depth': 8, 'learning_rate': 0.010165366737929627, 'n_estimators': 830, 'reg_lambda': 5.02933862017341, 'subsample': 0.7178565979183853, 'colsample_bytree': 0.6888728769554779}
Best trial: 16. Best value: 16.9064: 100%|██████████| 20/20 [33:43<00:00, 101.20s/it]
2026-09-03 16:16:16 | INFO | hyperparameter_tuner.py | Line:154 | [xgboost] Optimization finished. Best MAE = 16.9064 at trial 16.
2026-09-03 16:16:16 | INFO | base_trainer.py | Line:74 | Training XGBRegressor...

[I 2026-09-03 16:16:16,901] Trial 19 finished with value: 16.91257667541504 and parameters: {'max_depth': 8, 'learning_rate': 0.010165366737929627, 'n_estimators': 830, 'reg_lambda': 5.02933862017341, 'subsample': 0.7178565979183853, 'colsample_bytree': 0.6888728769554779}. Best is trial 16 with value: 16.906381607055664.
xgboost best params: {'random_state': 42, 'objective': 'reg:squarederror', 'max_depth': 8, 'learning_rate': 0.01023651005379198, 'n_estimators': 763, 'reg_lambda': 3.6736039846577295, 'subsample': 0.712949409808687, 'colsample_bytree': 0.6286191428179753}

2026-09-03 16:16:59 | INFO | base_trainer.py | Line:80 | Training completed successfully in 42.21s.
2026-09-03 16:16:59 | INFO | base_trainer.py | Line:129 | Generating predictions using XGBRegressor...
2026-09-03 16:16:59 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:16:59 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:16:59 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:17:04 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:17:04 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=4bea50c824c1481e84a12a222f95aa9b
[I 2026-09-03 16:17:04,270] A new study created in memory with name: lightgbm_rul_optimization
2026-09-03 16:17:04 | INFO | hyperparameter_tuner.py | Line:142 | Starting Optuna search for lightgbm: 20 trials, search space = ['max_depth', 'num_leaves', 'learning_rate', 'n_estimators', 'reg_lambda', 'subsample', 'colsample_bytree']

xgboost final validation metrics: {'MAE': 16.906381607055664, 'RMSE': 24.22747826590708, 'R2': 0.7662606239318848, 'MAPE': 24.818658168322965, 'Training Time (s)': 42.21}

--- Tuning lightgbm ---

  0%|          | 0/20 [00:00<?, ?it/s]2026-09-03 16:17:04 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...
2026-09-03 16:17:11 | INFO | base_trainer.py | Line:80 | Training completed successfully in 6.75s.
2026-09-03 16:17:11 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:17:11 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:17:11 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:17:11 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:17:23 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:17:23 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=b848cb7a3c92459398b6a0d141623865
2026-09-03 16:17:23 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 0 | MAE=17.5420 | RMSE=24.7962 | R2=0.7552 | Time=19.53s | params={'max_depth': 5, 'num_leaves': 244, 'learning_rate': 0.1205712628744377, 'n_estimators': 978, 'reg_lambda': 2.4041677639819286, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998}
Best trial: 0. Best value: 17.542:   5%|▌         | 1/20 [00:19<06:11, 19.56s/it]2026-09-03 16:17:23 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:17:23,820] Trial 0 finished with value: 17.541972991414273 and parameters: {'max_depth': 5, 'num_leaves': 244, 'learning_rate': 0.1205712628744377, 'n_estimators': 978, 'reg_lambda': 2.4041677639819286, 'subsample': 0.5779972601681014, 'colsample_bytree': 0.5290418060840998}. Best is trial 0 with value: 17.541972991414273.

2026-09-03 16:17:29 | INFO | base_trainer.py | Line:80 | Training completed successfully in 5.77s.
2026-09-03 16:17:29 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:17:29 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:17:29 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:17:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:17:38 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:17:38 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=9780c496d2924b56a7ee2aedd1568a8c
2026-09-03 16:17:38 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 1 | MAE=17.1549 | RMSE=24.5865 | R2=0.7593 | Time=15.06s | params={'max_depth': 9, 'num_leaves': 159, 'learning_rate': 0.11114989443094977, 'n_estimators': 226, 'reg_lambda': 9.72918866945795, 'subsample': 0.9162213204002109, 'colsample_bytree': 0.6061695553391381}
Best trial: 1. Best value: 17.1549:  10%|█         | 2/20 [00:34<05:04, 16.91s/it]2026-09-03 16:17:38 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:17:38,891] Trial 1 finished with value: 17.15494722673119 and parameters: {'max_depth': 9, 'num_leaves': 159, 'learning_rate': 0.11114989443094977, 'n_estimators': 226, 'reg_lambda': 9.72918866945795, 'subsample': 0.9162213204002109, 'colsample_bytree': 0.6061695553391381}. Best is trial 1 with value: 17.15494722673119.

2026-09-03 16:17:45 | INFO | base_trainer.py | Line:80 | Training completed successfully in 6.62s.
2026-09-03 16:17:45 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:17:45 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:17:45 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:17:46 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:17:55 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:17:55 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=ecf33cd9043e4763a023d2f25ea2d2cf
2026-09-03 16:17:55 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 2 | MAE=17.3250 | RMSE=24.4586 | R2=0.7618 | Time=16.28s | params={'max_depth': 4, 'num_leaves': 59, 'learning_rate': 0.028145092716060652, 'n_estimators': 882, 'reg_lambda': 4.887505167779041, 'subsample': 0.645614570099021, 'colsample_bytree': 0.8059264473611898}
Best trial: 1. Best value: 17.1549:  15%|█▌        | 3/20 [00:50<04:42, 16.63s/it]2026-09-03 16:17:55 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:17:55,181] Trial 2 finished with value: 17.325002817029283 and parameters: {'max_depth': 4, 'num_leaves': 59, 'learning_rate': 0.028145092716060652, 'n_estimators': 882, 'reg_lambda': 4.887505167779041, 'subsample': 0.645614570099021, 'colsample_bytree': 0.8059264473611898}. Best is trial 1 with value: 17.15494722673119.

2026-09-03 16:18:00 | INFO | base_trainer.py | Line:80 | Training completed successfully in 5.39s.
2026-09-03 16:18:00 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:18:00 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:18:00 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:18:01 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:18:10 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:18:10 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=280ca23ccd764ca5b15b644003aded71
2026-09-03 16:18:10 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 3 | MAE=17.3522 | RMSE=24.4767 | R2=0.7614 | Time=15.12s | params={'max_depth': 4, 'num_leaves': 85, 'learning_rate': 0.03476649150592621, 'n_estimators': 793, 'reg_lambda': 8.066583652537123, 'subsample': 0.5998368910791798, 'colsample_bytree': 0.7571172192068059}
Best trial: 1. Best value: 17.1549:  20%|██        | 4/20 [01:06<04:16, 16.04s/it]2026-09-03 16:18:10 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:18:10,311] Trial 3 finished with value: 17.352241048015046 and parameters: {'max_depth': 4, 'num_leaves': 85, 'learning_rate': 0.03476649150592621, 'n_estimators': 793, 'reg_lambda': 8.066583652537123, 'subsample': 0.5998368910791798, 'colsample_bytree': 0.7571172192068059}. Best is trial 1 with value: 17.15494722673119.

2026-09-03 16:18:15 | INFO | base_trainer.py | Line:80 | Training completed successfully in 4.90s.
2026-09-03 16:18:15 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:18:15 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:18:15 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:18:15 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:18:25 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:18:25 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=5f797dc08a144bb19545a78a6c05961f
2026-09-03 16:18:25 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 4 | MAE=17.2400 | RMSE=24.6422 | R2=0.7582 | Time=14.80s | params={'max_depth': 7, 'num_leaves': 26, 'learning_rate': 0.07896186801026692, 'n_estimators': 421, 'reg_lambda': 1.5854643368675156, 'subsample': 0.9744427686266666, 'colsample_bytree': 0.9828160165372797}
Best trial: 1. Best value: 17.1549:  25%|██▌       | 5/20 [01:20<03:53, 15.60s/it]2026-09-03 16:18:25 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:18:25,130] Trial 4 finished with value: 17.239965545141963 and parameters: {'max_depth': 7, 'num_leaves': 26, 'learning_rate': 0.07896186801026692, 'n_estimators': 421, 'reg_lambda': 1.5854643368675156, 'subsample': 0.9744427686266666, 'colsample_bytree': 0.9828160165372797}. Best is trial 1 with value: 17.15494722673119.

2026-09-03 16:18:47 | INFO | base_trainer.py | Line:80 | Training completed successfully in 22.57s.
2026-09-03 16:18:47 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:18:48 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:18:48 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:18:48 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:18:58 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:18:59 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=33189d0782dd44e9a72e7866b499b853
2026-09-03 16:18:59 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 5 | MAE=16.9676 | RMSE=24.3809 | R2=0.7633 | Time=33.91s | params={'max_depth': 9, 'num_leaves': 88, 'learning_rate': 0.013940346079873234, 'n_estimators': 1090, 'reg_lambda': 4.961372443656412, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351}
Best trial: 5. Best value: 16.9676:  30%|███       | 6/20 [01:54<05:05, 21.83s/it]2026-09-03 16:18:59 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:18:59,050] Trial 5 finished with value: 16.96757636081599 and parameters: {'max_depth': 9, 'num_leaves': 88, 'learning_rate': 0.013940346079873234, 'n_estimators': 1090, 'reg_lambda': 4.961372443656412, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.7475884550556351}. Best is trial 5 with value: 16.96757636081599.

2026-09-03 16:19:13 | INFO | base_trainer.py | Line:80 | Training completed successfully in 14.58s.
2026-09-03 16:19:13 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:19:14 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:19:14 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:19:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:19:29 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:19:29 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=6ad25ab97d9f47d290c8de7ec300a538
2026-09-03 16:19:29 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 6 | MAE=17.6074 | RMSE=24.6330 | R2=0.7584 | Time=30.82s | params={'max_depth': 3, 'num_leaves': 234, 'learning_rate': 0.024112898115291985, 'n_estimators': 1061, 'reg_lambda': 3.8053996848046987, 'subsample': 0.7600340105889054, 'colsample_bytree': 0.7733551396716398}
Best trial: 5. Best value: 16.9676:  35%|███▌      | 7/20 [02:25<05:22, 24.78s/it]2026-09-03 16:19:29 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:19:29,888] Trial 6 finished with value: 17.60737861989084 and parameters: {'max_depth': 3, 'num_leaves': 234, 'learning_rate': 0.024112898115291985, 'n_estimators': 1061, 'reg_lambda': 3.8053996848046987, 'subsample': 0.7600340105889054, 'colsample_bytree': 0.7733551396716398}. Best is trial 5 with value: 16.96757636081599.

2026-09-03 16:19:42 | INFO | base_trainer.py | Line:80 | Training completed successfully in 12.12s.
2026-09-03 16:19:42 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:19:42 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:19:42 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:19:42 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:19:53 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:19:53 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=1bfaf583a0b04962bdeaa2bc81ef8a3a
2026-09-03 16:19:53 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 7 | MAE=17.6383 | RMSE=24.8264 | R2=0.7546 | Time=23.73s | params={'max_depth': 4, 'num_leaves': 248, 'learning_rate': 0.13962563737015762, 'n_estimators': 1422, 'reg_lambda': 9.053446153848839, 'subsample': 0.7989499894055425, 'colsample_bytree': 0.9609371175115584}
Best trial: 5. Best value: 16.9676:  40%|████      | 8/20 [02:49<04:53, 24.44s/it]2026-09-03 16:19:53 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:19:53,628] Trial 7 finished with value: 17.63829083683552 and parameters: {'max_depth': 4, 'num_leaves': 248, 'learning_rate': 0.13962563737015762, 'n_estimators': 1422, 'reg_lambda': 9.053446153848839, 'subsample': 0.7989499894055425, 'colsample_bytree': 0.9609371175115584}. Best is trial 5 with value: 16.96757636081599.

2026-09-03 16:19:58 | INFO | base_trainer.py | Line:80 | Training completed successfully in 4.90s.
2026-09-03 16:19:58 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:19:58 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:19:58 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:19:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:20:09 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:20:09 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=8836909ab35e4832926ab4e65655d4d4
2026-09-03 16:20:09 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 8 | MAE=17.9806 | RMSE=24.9831 | R2=0.7515 | Time=15.79s | params={'max_depth': 3, 'num_leaves': 62, 'learning_rate': 0.011662890273931383, 'n_estimators': 623, 'reg_lambda': 4.498095607205338, 'subsample': 0.6356745158869479, 'colsample_bytree': 0.9143687545759647}
Best trial: 5. Best value: 16.9676:  45%|████▌     | 9/20 [03:05<03:59, 21.74s/it]2026-09-03 16:20:09 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:20:09,433] Trial 8 finished with value: 17.980573592298303 and parameters: {'max_depth': 3, 'num_leaves': 62, 'learning_rate': 0.011662890273931383, 'n_estimators': 623, 'reg_lambda': 4.498095607205338, 'subsample': 0.6356745158869479, 'colsample_bytree': 0.9143687545759647}. Best is trial 5 with value: 16.96757636081599.

2026-09-03 16:20:14 | INFO | base_trainer.py | Line:80 | Training completed successfully in 5.19s.
2026-09-03 16:20:14 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:20:14 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:20:14 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:20:14 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:20:25 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:20:25 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=7718245e477541d4b3c15af222d0d433
2026-09-03 16:20:25 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 9 | MAE=17.2237 | RMSE=24.5114 | R2=0.7608 | Time=16.07s | params={'max_depth': 5, 'num_leaves': 82, 'learning_rate': 0.06333268775321843, 'n_estimators': 383, 'reg_lambda': 8.219772826786357, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9934434683002586}
Best trial: 5. Best value: 16.9676:  50%|█████     | 10/20 [03:21<03:19, 20.00s/it]2026-09-03 16:20:25 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:20:25,512] Trial 9 finished with value: 17.22370703300724 and parameters: {'max_depth': 5, 'num_leaves': 82, 'learning_rate': 0.06333268775321843, 'n_estimators': 383, 'reg_lambda': 8.219772826786357, 'subsample': 0.5372753218398854, 'colsample_bytree': 0.9934434683002586}. Best is trial 5 with value: 16.96757636081599.

2026-09-03 16:21:06 | INFO | base_trainer.py | Line:80 | Training completed successfully in 41.29s.
2026-09-03 16:21:06 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:21:09 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:21:09 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:21:09 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:21:21 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:21:21 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=173bfc670a5a4680b551bb7bf69a8c86
2026-09-03 16:21:21 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 10 | MAE=18.1447 | RMSE=25.6188 | R2=0.7386 | Time=56.09s | params={'max_depth': 10, 'num_leaves': 149, 'learning_rate': 0.2704729722717776, 'n_estimators': 1412, 'reg_lambda': 6.37707309301379, 'subsample': 0.7704719540877739, 'colsample_bytree': 0.6524547591273671}
Best trial: 5. Best value: 16.9676:  55%|█████▌    | 11/20 [04:17<04:39, 31.05s/it]2026-09-03 16:21:21 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:21:21,640] Trial 10 finished with value: 18.144672102248315 and parameters: {'max_depth': 10, 'num_leaves': 149, 'learning_rate': 0.2704729722717776, 'n_estimators': 1412, 'reg_lambda': 6.37707309301379, 'subsample': 0.7704719540877739, 'colsample_bytree': 0.6524547591273671}. Best is trial 5 with value: 16.96757636081599.

2026-09-03 16:21:30 | INFO | base_trainer.py | Line:80 | Training completed successfully in 8.50s.
2026-09-03 16:21:30 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:21:30 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:21:30 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:21:30 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:21:41 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:21:41 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=9cfde8bf8d20448da9afd5e885f342bc
2026-09-03 16:21:41 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 11 | MAE=18.3748 | RMSE=24.1587 | R2=0.7676 | Time=19.97s | params={'max_depth': 9, 'num_leaves': 151, 'learning_rate': 0.010299649680284932, 'n_estimators': 250, 'reg_lambda': 6.55709025693719, 'subsample': 0.946069909070392, 'colsample_bytree': 0.6285647093894122}
Best trial: 5. Best value: 16.9676:  60%|██████    | 12/20 [04:37<03:41, 27.69s/it]2026-09-03 16:21:41 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:21:41,650] Trial 11 finished with value: 18.374810107749536 and parameters: {'max_depth': 9, 'num_leaves': 151, 'learning_rate': 0.010299649680284932, 'n_estimators': 250, 'reg_lambda': 6.55709025693719, 'subsample': 0.946069909070392, 'colsample_bytree': 0.6285647093894122}. Best is trial 5 with value: 16.96757636081599.

2026-09-03 16:22:18 | INFO | base_trainer.py | Line:80 | Training completed successfully in 36.68s.
2026-09-03 16:22:18 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:22:19 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:22:19 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:22:19 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:22:32 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:22:32 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=2ab4b7c12e4144e9b8f37d05aedee9ac
2026-09-03 16:22:32 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 12 | MAE=18.1116 | RMSE=25.4971 | R2=0.7411 | Time=50.49s | params={'max_depth': 8, 'num_leaves': 145, 'learning_rate': 0.2682983926090437, 'n_estimators': 1198, 'reg_lambda': 6.356667967155804, 'subsample': 0.8889742890162072, 'colsample_bytree': 0.6584399635185049}
Best trial: 5. Best value: 16.9676:  65%|██████▌   | 13/20 [05:27<04:02, 34.61s/it]2026-09-03 16:22:32 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:22:32,178] Trial 12 finished with value: 18.11156747873903 and parameters: {'max_depth': 8, 'num_leaves': 145, 'learning_rate': 0.2682983926090437, 'n_estimators': 1198, 'reg_lambda': 6.356667967155804, 'subsample': 0.8889742890162072, 'colsample_bytree': 0.6584399635185049}. Best is trial 5 with value: 16.96757636081599.

2026-09-03 16:22:50 | INFO | base_trainer.py | Line:80 | Training completed successfully in 17.91s.
2026-09-03 16:22:50 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:22:50 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:22:50 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:22:50 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:23:02 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:23:02 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=f2d3765d5bcd4182b7c324b963f6d7b2
2026-09-03 16:23:02 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 13 | MAE=17.0087 | RMSE=24.3753 | R2=0.7634 | Time=30.05s | params={'max_depth': 10, 'num_leaves': 200, 'learning_rate': 0.04944752449549738, 'n_estimators': 652, 'reg_lambda': 9.786926066971784, 'subsample': 0.7038139017920023, 'colsample_bytree': 0.5370578742866865}
Best trial: 5. Best value: 16.9676:  70%|███████   | 14/20 [05:57<03:19, 33.24s/it]2026-09-03 16:23:02 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:23:02,257] Trial 13 finished with value: 17.00866530784911 and parameters: {'max_depth': 10, 'num_leaves': 200, 'learning_rate': 0.04944752449549738, 'n_estimators': 652, 'reg_lambda': 9.786926066971784, 'subsample': 0.7038139017920023, 'colsample_bytree': 0.5370578742866865}. Best is trial 5 with value: 16.96757636081599.

2026-09-03 16:23:23 | INFO | base_trainer.py | Line:80 | Training completed successfully in 21.15s.
2026-09-03 16:23:23 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:23:24 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:23:24 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:23:24 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:23:36 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:23:36 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=4684a1fe84da49f5bb6f00a70d803d91
2026-09-03 16:23:36 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 14 | MAE=16.9047 | RMSE=24.2479 | R2=0.7659 | Time=34.00s | params={'max_depth': 10, 'num_leaves': 188, 'learning_rate': 0.015401818885932124, 'n_estimators': 687, 'reg_lambda': 3.0250870556045992, 'subsample': 0.6980786230998579, 'colsample_bytree': 0.5562286377634573}
Best trial: 14. Best value: 16.9047:  75%|███████▌  | 15/20 [06:32<02:47, 33.48s/it]2026-09-03 16:23:36 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:23:36,279] Trial 14 finished with value: 16.904740768572346 and parameters: {'max_depth': 10, 'num_leaves': 188, 'learning_rate': 0.015401818885932124, 'n_estimators': 687, 'reg_lambda': 3.0250870556045992, 'subsample': 0.6980786230998579, 'colsample_bytree': 0.5562286377634573}. Best is trial 14 with value: 16.904740768572346.

2026-09-03 16:24:00 | INFO | base_trainer.py | Line:80 | Training completed successfully in 23.69s.
2026-09-03 16:24:00 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:24:00 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:24:01 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:24:01 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:24:12 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:24:12 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=dd6e372f9b1244d893ac4be991475f42
2026-09-03 16:24:12 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 15 | MAE=16.9913 | RMSE=24.4233 | R2=0.7625 | Time=36.25s | params={'max_depth': 7, 'num_leaves': 108, 'learning_rate': 0.017176735494261273, 'n_estimators': 1211, 'reg_lambda': 3.0427762582073354, 'subsample': 0.5289562460538045, 'colsample_bytree': 0.850918512516425}
Best trial: 14. Best value: 16.9047:  80%|████████  | 16/20 [07:08<02:17, 34.32s/it]2026-09-03 16:24:12 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:24:12,562] Trial 15 finished with value: 16.991281528104246 and parameters: {'max_depth': 7, 'num_leaves': 108, 'learning_rate': 0.017176735494261273, 'n_estimators': 1211, 'reg_lambda': 3.0427762582073354, 'subsample': 0.5289562460538045, 'colsample_bytree': 0.850918512516425}. Best is trial 14 with value: 16.904740768572346.

2026-09-03 16:24:36 | INFO | base_trainer.py | Line:80 | Training completed successfully in 24.19s.
2026-09-03 16:24:36 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:24:37 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:24:37 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:24:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:24:48 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:24:48 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=ee53166caa914d298ad282832a9173ce
2026-09-03 16:24:48 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 16 | MAE=16.8588 | RMSE=24.2569 | R2=0.7657 | Time=36.11s | params={'max_depth': 9, 'num_leaves': 205, 'learning_rate': 0.017036761422804702, 'n_estimators': 700, 'reg_lambda': 5.42342883182045, 'subsample': 0.7028276948665404, 'colsample_bytree': 0.7140790889786011}
Best trial: 16. Best value: 16.8588:  85%|████████▌ | 17/20 [07:44<01:44, 34.89s/it]2026-09-03 16:24:48 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:24:48,756] Trial 16 finished with value: 16.85882798236743 and parameters: {'max_depth': 9, 'num_leaves': 205, 'learning_rate': 0.017036761422804702, 'n_estimators': 700, 'reg_lambda': 5.42342883182045, 'subsample': 0.7028276948665404, 'colsample_bytree': 0.7140790889786011}. Best is trial 16 with value: 16.85882798236743.

2026-09-03 16:25:06 | INFO | base_trainer.py | Line:80 | Training completed successfully in 17.58s.
2026-09-03 16:25:06 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:25:06 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:25:06 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:25:07 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:25:18 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:25:18 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=02f0dc38129641c198af84580793b96a
2026-09-03 16:25:18 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 17 | MAE=16.8725 | RMSE=24.2743 | R2=0.7654 | Time=29.42s | params={'max_depth': 8, 'num_leaves': 196, 'learning_rate': 0.0189273731882151, 'n_estimators': 614, 'reg_lambda': 1.4567270666237337, 'subsample': 0.703891454546058, 'colsample_bytree': 0.707531628592797}
Best trial: 16. Best value: 16.8588:  90%|█████████ | 18/20 [08:13<01:06, 33.25s/it]2026-09-03 16:25:18 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:25:18,208] Trial 17 finished with value: 16.872515992857753 and parameters: {'max_depth': 8, 'num_leaves': 196, 'learning_rate': 0.0189273731882151, 'n_estimators': 614, 'reg_lambda': 1.4567270666237337, 'subsample': 0.703891454546058, 'colsample_bytree': 0.707531628592797}. Best is trial 16 with value: 16.85882798236743.

2026-09-03 16:25:28 | INFO | base_trainer.py | Line:80 | Training completed successfully in 10.66s.
2026-09-03 16:25:28 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:25:29 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:25:29 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:25:29 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:25:40 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:25:40 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=5571964cee924f44952c894e8be3b5fd
2026-09-03 16:25:40 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 18 | MAE=16.9671 | RMSE=24.3516 | R2=0.7639 | Time=22.04s | params={'max_depth': 7, 'num_leaves': 207, 'learning_rate': 0.021421143670963927, 'n_estimators': 498, 'reg_lambda': 1.0078205358950156, 'subsample': 0.8395603438976386, 'colsample_bytree': 0.6991862007751071}
Best trial: 16. Best value: 16.8588:  95%|█████████▌| 19/20 [08:36<00:29, 29.89s/it]2026-09-03 16:25:40 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:25:40,282] Trial 18 finished with value: 16.96713331900573 and parameters: {'max_depth': 7, 'num_leaves': 207, 'learning_rate': 0.021421143670963927, 'n_estimators': 498, 'reg_lambda': 1.0078205358950156, 'subsample': 0.8395603438976386, 'colsample_bytree': 0.6991862007751071}. Best is trial 16 with value: 16.85882798236743.

2026-09-03 16:25:59 | INFO | base_trainer.py | Line:80 | Training completed successfully in 19.39s.
2026-09-03 16:25:59 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:26:00 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:26:00 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:26:00 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:26:11 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:26:11 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=10f3ea92bafd4d2f9160d90c0ab66218
2026-09-03 16:26:11 | INFO | hyperparameter_tuner.py | Line:219 | [lightgbm] Trial 19 | MAE=17.0552 | RMSE=24.4914 | R2=0.7611 | Time=31.04s | params={'max_depth': 8, 'num_leaves': 220, 'learning_rate': 0.04323444823345436, 'n_estimators': 789, 'reg_lambda': 5.70412638741382, 'subsample': 0.6991394112624664, 'colsample_bytree': 0.7059109128166592}
Best trial: 16. Best value: 16.8588: 100%|██████████| 20/20 [09:07<00:00, 27.35s/it]
2026-09-03 16:26:11 | INFO | hyperparameter_tuner.py | Line:154 | [lightgbm] Optimization finished. Best MAE = 16.8588 at trial 16.
2026-09-03 16:26:11 | INFO | base_trainer.py | Line:74 | Training LGBMRegressor...

[I 2026-09-03 16:26:11,354] Trial 19 finished with value: 17.055227113934727 and parameters: {'max_depth': 8, 'num_leaves': 220, 'learning_rate': 0.04323444823345436, 'n_estimators': 789, 'reg_lambda': 5.70412638741382, 'subsample': 0.6991394112624664, 'colsample_bytree': 0.7059109128166592}. Best is trial 16 with value: 16.85882798236743.
lightgbm best params: {'random_state': 42, 'verbose': -1, 'max_depth': 9, 'num_leaves': 205, 'learning_rate': 0.017036761422804702, 'n_estimators': 700, 'reg_lambda': 5.42342883182045, 'subsample': 0.7028276948665404, 'colsample_bytree': 0.7140790889786011}

2026-09-03 16:26:34 | INFO | base_trainer.py | Line:80 | Training completed successfully in 22.72s.
2026-09-03 16:26:34 | INFO | base_trainer.py | Line:129 | Generating predictions using LGBMRegressor...
2026-09-03 16:26:34 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:26:34 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026/09/03 16:26:35 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/09/03 16:26:46 WARNING mlflow.utils.environment: Failed to resolve installed pip version. ``pip`` will be added to conda.yaml environment spec without a version specifier.
2026-09-03 16:26:46 | INFO | base_trainer.py | Line:99 | Logged to MLflow: run_id=b6f1f3d602b74753baac3c3a48fd6cde

lightgbm final validation metrics: {'MAE': 16.85882798236743, 'RMSE': 24.256890487984794, 'R2': 0.7656927363098012, 'MAPE': 24.657215414509423, 'Training Time (s)': 22.72}

## 9- Build the Ensemble

In [13]:
val_mae_by_model = {r["Model"]: r["MAE"] for r in val_results}
ensemble = EnsembleModel.from_inverse_mae(tuned_models, val_mae_by_model)

ensemble_val_preds = ensemble.predict(X_val)
ensemble_val_metrics = evaluator.evaluate(y_val, ensemble_val_preds)
print(f"Ensemble weights: {ensemble.weights}")
print(f"Ensemble validation metrics: {ensemble_val_metrics}")

val_results.append({"Model": "ensemble", "Stage": "tuned_ensemble", **ensemble_val_metrics})

ENSEMBLE_DIR = MODELS_DIR / "ensemble_regime_aware"
ENSEMBLE_DIR.mkdir(parents=True, exist_ok=True)
ensemble.save(ENSEMBLE_DIR)
print(f"Saved -> {ENSEMBLE_DIR}")

2026-09-03 16:33:33 | INFO | ensemble.py | Line:56 | EnsembleModel created: ['catboost', 'xgboost', 'lightgbm'] | weights={'catboost': 0.3316147623162496, 'xgboost': 0.33372195478963834, 'lightgbm': 0.33466328289411207}
2026-09-03 16:33:34 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:33:34 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.

Ensemble weights: {'catboost': 0.3316147623162496, 'xgboost': 0.33372195478963834, 'lightgbm': 0.33466328289411207}
Ensemble validation metrics: {'MAE': 16.8295492825387, 'RMSE': 24.13877598463981, 'R2': 0.7679690137826243, 'MAPE': 24.50875919797251}

2026-09-03 16:33:34 | INFO | ensemble.py | Line:97 | EnsembleModel saved to A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\ensemble_regime_aware

Saved -> A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\artifacts\models\ensemble_regime_aware

## 10- Validation Comparison

In [14]:
val_results_df = pd.DataFrame(val_results)
REPORTS_DIR.mkdir(parents=True, exist_ok=True)
val_results_df.to_csv(REPORTS_DIR / "regime_aware_ensemble_validation_results.csv", index=False)
val_results_df.sort_values("MAE")

,Model,Stage,MAE,RMSE,R2,MAPE,Training Time (s)
3,ensemble,tuned_ensemble,16.829549,24.138776,0.767969,24.508759,NaN
2,lightgbm,tuned_individual,16.858828,24.256890,0.765693,24.657215,22.72
1,xgboost,tuned_individual,16.906382,24.227478,0.766261,24.818658,42.21
0,catboost,tuned_individual,17.013810,24.180506,0.767166,25.310100,101.04

## 11- Official Test-Set Evaluation & Comparison to Prior Best

In [15]:
if RUN_TEST_EVAL:
    test_features_df = engineer.transform(test_raw)
    last_rows = (
        test_features_df.sort_values([ENGINE_COLUMN, "time_in_cycles"])
        .groupby(ENGINE_COLUMN).tail(1).sort_values(ENGINE_COLUMN).reset_index(drop=True)
    )

    X_test = scaler.transform(last_rows[final_features])
    y_test_true = rul_raw["RUL"].to_numpy()

    test_results = []
    for model_name, model in tuned_models.items():
        preds = model.predict(X_test)
        metrics = evaluator.evaluate(y_test_true, preds)
        test_results.append({"Model": model_name, "Stage": "tuned_individual", **metrics})

    ensemble_test_preds = ensemble.predict(X_test)
    ensemble_test_metrics = evaluator.evaluate(y_test_true, ensemble_test_preds)
    test_results.append({"Model": "ensemble", "Stage": "tuned_ensemble", **ensemble_test_metrics})

    test_results_df = pd.DataFrame(test_results)
    test_results_df.to_csv(REPORTS_DIR / "regime_aware_ensemble_test_results.csv", index=False)
    display(test_results_df.sort_values("MAE"))

    print("\nPrior best (non-regime-aware, globally-scaled ensemble): test MAE = 19.226")
    best_row = test_results_df.loc[test_results_df["MAE"].idxmin()]
    print(f"This run's best ({best_row['Model']}): test MAE = {best_row['MAE']:.3f}")
else:
    print("Skipped (RUN_TEST_EVAL=False)")

2026-09-03 16:33:48 | INFO | feature_engineer.py | Line:50 | Starting Feature Engineering...
2026-09-03 16:33:48 | INFO | feature_engineer.py | Line:119 | Generating Rolling Mean features...
2026-09-03 16:33:49 | INFO | feature_engineer.py | Line:148 | Generating Rolling Std features...
2026-09-03 16:33:50 | INFO | feature_engineer.py | Line:179 | Generating Lag Features...
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:189: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
2026-09-03 16:33:50 | INFO | feature_engineer.py | Line:205 | Generating Rate of Change features...
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
A:\AI_Engineer\ML Projects\Predictive-Maintenance-RUL\src\preprocessing\feature_engineer.py:213: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[feature_name] = (
2026-09-03 16:33:50 | INFO | feature_engineer.py | Line:61 | Feature Engineering completed successfully.
2026-09-03 16:33:50 | INFO | feature_scaler.py | Line:44 | Transforming features...
2026-09-03 16:33:50 | INFO | feature_scaler.py | Line:60 | Feature transformation completed.
2026-09-03 16:33:50 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:33:50 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-09-03 16:33:50 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:33:50 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-09-03 16:33:50 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:33:50 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.
2026-09-03 16:33:50 | INFO | evaluator.py | Line:47 | Starting regression evaluation...
2026-09-03 16:33:50 | INFO | evaluator.py | Line:80 | Evaluation completed successfully.

      Model             Stage        MAE       RMSE        R2       MAPE
0  catboost  tuned_individual  19.132785  25.367345  0.783540  28.446220
3  ensemble    tuned_ensemble  19.247538  25.335927  0.784076  28.010054
1   xgboost  tuned_individual  19.428778  25.299473  0.784697  28.744324
2  lightgbm  tuned_individual  19.579705  25.629934  0.779035  28.435882

Prior best (non-regime-aware, globally-scaled ensemble): test MAE = 19.226
This run's best (catboost): test MAE = 19.133

## Conclusion

- **Verified end-to-end** with a small trial count (2 per model) before delivery -- zero errors, and even at this minimal search, the regime-aware ensemble already beat the prior best (test MAE 19.173 vs 19.226).
- **The controlled A/B experiment already proved the mechanism works** (`regime_normalization_experiment.py`): with hyperparameters held completely fixed, regime-aware normalization alone improved every metric on both validation and test. This notebook builds on that confirmed result rather than assuming it.
- **`N_TRIALS` is set to 20** above -- increase to 30-50 for a more thorough search. Every trial (for all three models, in both the original and this regime-aware pipeline) is in MLflow, filterable by `tags.normalization = "regime_aware"`.
- If this run's test MAE beats 19.226 by a meaningful margin (not just noise), this regime-aware pipeline should become the new canonical one -- promote `regime_normalizer.pkl`, `feature_scaler_regime_aware.pkl`, and `selected_features_regime_aware.json` to their non-suffixed canonical names, and update the main pipeline to include the regime-normalization step by default.